decks = {
    "Phrases": [
        ("the morning", "la mañana"),
        ("from where", "de dónde"),
        ("What are you doing this afternoon?", "¿Qué haces esta tarde?"),
        ("to review / revise", "repasar"),
        ("What do you mean, why?", "¿Qué por qué?"),
        ("What day is it today?", "¿Qué día es hoy?"),
        ("clear as water", "clara como el agua"),
        ("Sorry, I don't know", "Lo siento, no lo sé"),
        ("Sorry, I don't speak Japanese", "Lo siento, no hablo japonés"),
        ("Sorry, I speak a bit of Spanish", "Lo siento, hablo un poco de español"),
        ("What does it mean?", "¿Qué significa?"),
        ("Hey, this afternoon I was thinking that you could go to the beach", "Mira, esta tarde estaba pensando que podrías ir a la playa"),
    ],

    "Verb Conjugations": [
        ("My name", "Me llamo (yo)"),
        ("Your name", "Te llamas (tú)"),
        ("His/Her name", "Se llama (él / ella)"),
        ("Their names", "Se llaman (ellos / ellas)"),
        ("Our names", "Nos llamamos (nosotros)"),
        ("You all names", "Os llamáis (vosotros)"),
        ("Formal your name", "Se llama (usted)"),
        ("(yo) como", "I eat"),
        ("yo como una manzana", "I eat an apple"),
        ("(tú) comes", "you eat"),
        ("tú comes pan", "you eat bread"),
        ("(él) come", "he eats"),
        ("él come arroz", "he eats rice"),
        ("(ella) come", "she eats"),
        ("ella come arroz", "she eats rice"),
        ("(usted) come", "you eat (formal)"),
        ("usted come arroz", "you eat rice (formal)"),
        ("(nosotros) comemos", "we eat"),
        ("nosotros comemos juntos", "we eat together"),
        ("(vosotros) coméis", "you all eat"),
        ("vosotros coméis tarde", "you all eat late"),
        ("(ellos) comen", "they eat (masc.)"),
        ("ellos comen en casa", "they eat at home (masc.)"),
        ("(ellas) comen", "they eat (fem.)"),
        ("ellas comen en casa", "they eat at home (fem.)"),
        ("(ustedes) comen", "you all eat (formal)"),
        ("ustedes comen en casa", "you all eat at home (formal)"),
        ("(yo) vivo", "I live"),
        ("yo vivo en Londres", "I live in London"),
        ("(tú) vives", "you live"),
        ("tú vives cerca", "you live nearby"),
        ("(él) vive", "he lives"),
        ("él vive solo", "he lives alone"),
        ("(ella) vive", "she lives"),
        ("ella vive sola", "she lives alone"),
        ("(usted) vive", "you live (formal)"),
        ("usted vive en Madrid", "you live in Madrid (formal)"),
        ("(nosotros) vivimos", "we live"),
        ("nosotros vivimos aquí", "we live here"),
        ("(vosotros) vivís", "you all live"),
        ("vosotros vivís lejos", "you all live far away"),
        ("(ellos) viven", "they live (masc.)"),
        ("ellos viven juntos", "they live together (masc.)"),
        ("(ellas) viven", "they live (fem.)"),
        ("ellas viven juntas", "they live together (fem.)"),
        ("(ustedes) viven", "you all live (formal)"),
        ("ustedes viven aquí", "you all live here (formal)"),
        ("(yo) trabajo", "I work"),
        ("yo trabajo mucho", "I work a lot"),
        ("(tú) trabajas", "you work"),
        ("tú trabajas en casa", "you work at home"),
        ("(él) trabaja", "he works"),
        ("él trabaja de camarero", "he works as a waiter"),
        ("(ella) trabaja", "she works"),
        ("ella trabaja de camarera", "she works as a waitress"),
        ("(usted) trabaja", "you work (formal)"),
        ("usted trabaja en una oficina", "you work in an office (formal)"),
        ("(nosotros) trabajamos", "we work"),
        ("nosotros trabajamos en un banco", "we work in a bank"),
        ("(vosotros) trabajáis", "you all work"),
        ("vosotros trabajáis poco", "you all work little"),
        ("(ellos) trabajan", "they work (masc.)"),
        ("ellos trabajan juntos", "they work together (masc.)"),
        ("(ellas) trabajan", "they work (fem.)"),
        ("ellas trabajan juntas", "they work together (fem.)"),
        ("(ustedes) trabajan", "you all work (formal)"),
        ("ustedes trabajan en una empresa", "you all work in a company (formal)"),
        ("(yo) canto", "I sing"),
        ("yo canto bien", "I sing well"),
        ("(tú) cantas", "you sing"),
        ("tú cantas en la ducha", "you sing in the shower"),
        ("(él) canta", "he sings"),
        ("él canta muy bonito", "he sings very beautifully"),
        ("(ella) canta", "she sings"),
        ("ella canta muy bonito", "she sings very beautifully"),
        ("(usted) canta", "you sing (formal)"),
        ("usted canta en el coro", "you sing in the choir (formal)"),
        ("(nosotros) cantamos", "we sing"),
        ("nosotros cantamos una canción", "we sing a song"),
        ("(vosotros) cantáis", "you all sing"),
        ("vosotros cantáis juntos", "you all sing together"),
        ("(ellos) cantan", "they sing (masc.)"),
        ("ellos cantan en un coro", "they sing in a choir (masc.)"),
        ("(ellas) cantan", "they sing (fem.)"),
        ("ellas cantan en un coro", "they sing in a choir (fem.)"),
        ("(ustedes) cantan", "you all sing (formal)"),
        ("ustedes cantan muy bien", "you all sing very well (formal)"),
        ("to be (location/state)", "estar"),
        ("to be (identity/characteristics)", "ser"),
        ("(yo) estoy", "I am"),
        ("yo estoy cansado", "I am tired"),
        ("(tú) estás", "you are"),
        ("tú estás feliz", "you are happy"),
        ("(él) está", "he is"),
        ("él está en casa", "he is at home"),
        ("(ella) está", "she is"),
        ("ella está en la escuela", "she is at school"),
        ("(usted) está", "you are (formal)"),
        ("usted está en la oficina", "you are in the office (formal)"),
        ("(nosotros) estamos", "we are (masc.)"),
        ("nosotros estamos en el parque", "we are in the park (masc.)"),
        ("(nosotras) estamos", "we are (fem.)"),
        ("nosotras estamos en el parque", "we are in the park (fem.)"),
        ("(vosotros) estáis", "you all are (masc.)"),
        ("vosotros estáis listos", "you all are ready (masc.)"),
        ("(vosotras) estáis", "you all are (fem.)"),
        ("vosotras estáis cansadas", "you all are tired (fem.)"),
        ("(ellos) están", "they are (masc.)"),
        ("ellos están ocupados", "they are busy (masc.)"),
        ("(ellas) están", "they are (fem.)"),
        ("ellas están contentas", "they are happy (fem.)"),
        ("(ustedes) están", "you all are (formal)"),
        ("ustedes están aquí", "you all are here (formal)"),
        ("(yo) soy", "I am"),
        ("yo soy estudiante", "I am a student"),
        ("(tú) eres", "you are"),
        ("tú eres simpático", "you are nice"),
        ("(él) es", "he is"),
        ("él es profesor", "he is a teacher"),
        ("(ella) es", "she is"),
        ("ella es médica", "she is a doctor"),
        ("(usted) es", "you are (formal)"),
        ("usted es muy amable", "you are very kind (formal)"),
        ("(nosotros) somos", "we are (masc.)"),
        ("nosotros somos amigos", "we are friends (masc.)"),
        ("(nosotras) somos", "we are (fem.)"),
        ("nosotras somos amigas", "we are friends (fem.)"),
        ("(vosotros) sois", "you all are (masc.)"),
        ("vosotros sois españoles", "you all are Spanish (masc.)"),
        ("(vosotras) sois", "you all are (fem.)"),
        ("vosotras sois españolas", "you all are Spanish (fem.)"),
        ("(ellos) son", "they are (masc.)"),
        ("ellos son ingenieros", "they are engineers (masc.)"),
        ("(ellas) son", "they are (fem.)"),
        ("ellas son enfermeras", "they are nurses (fem.)"),
        ("(ustedes) son", "you all are (formal)"),
        ("ustedes son de México", "you all are from Mexico (formal)"),
        ("The books are in the library", "los libros están en la biblioteca"),
        ("We are concentrated", "nosotros estamos concentrados"),
        ("Are you busy?", "¿está usted ocupado?"),
        ("No, I am not busy", "no, (yo) no estoy ocupado"),
        ("You all are concentrated", "vosotros estáis concentrados"),
        ("to have", "tener"),
        ("(yo) tengo", "I have"),
        ("yo tengo un coche", "I have a car"),
        ("(tú) tienes", "you have"),
        ("tú tienes una casa", "you have a house"),
        ("(él) tiene", "he has"),
        ("él tiene un perro", "he has a dog"),
        ("(ella) tiene", "she has"),
        ("ella tiene un gato", "she has a cat"),
        ("(usted) tiene", "you have (formal)"),
        ("usted tiene una cita", "you have an appointment (formal)"),
        ("(nosotros) tenemos", "we have (masc.)"),
        ("nosotros tenemos hambre", "we are hungry (masc.)"),
        ("(nosotras) tenemos", "we have (fem.)"),
        ("nosotras tenemos hambre", "we are hungry (fem.)"),
        ("(vosotros) tenéis", "you all have (masc.)"),
        ("vosotros tenéis frío", "you all are cold (masc.)"),
        ("(vosotras) tenéis", "you all have (fem.)"),
        ("vosotras tenéis sueño", "you all are sleepy (fem.)"),
        ("(ellos) tienen", "they have (masc.)"),
        ("ellos tienen dinero", "they have money (masc.)"),
        ("(ellas) tienen", "they have (fem.)"),
        ("ellas tienen suerte", "they are lucky (fem.)"),
        ("(ustedes) tienen", "you all have (formal)"),
        ("ustedes tienen razón", "you all are right (formal)"),
    ],

    "Help": [
        ("how", "cómo"),
        ("What did you say?", "¿Cómo dices?"),
        ('What does "vale" mean?', '¿Qué significa "vale"?'),
        ('How do you say "water" in Spanish?', '¿Cómo se dice "water" en español?'),
        ("How do you say this in Spanish?", "¿Cómo se dice esto en español?"),
        ("Can you speak louder, please?", "¿Puedes hablar más alto, por favor?"),
        ("Can you speak more slowly, please?", "¿Puedes hablar más despacio, por favor?"),
        ("Can you repeat, please?", "¿Puedes repetir, por favor?"),
        ("to be able to (infinitive form of puedo)", "poder"),
        ("I can", "yo puedo"),
    ],

    "Numbers": [
        ("one", "uno"),
        ("two", "dos"),
        ("three", "tres"),
        ("four", "cuatro"),
        ("five", "cinco"),
        ("six", "seis"),
        ("seven", "siete"),
        ("eight", "ocho"),
        ("nine", "nueve"),
        ("ten", "diez"),
        ("eleven", "once"),
        ("twelve", "doce"),
        ("thirteen", "trece"),
        ("fourteen", "catorce"),
        ("fifteen", "quince"),
        ("sixteen", "dieciséis"),
        ("seventeen", "diecisiete"),
        ("eighteen", "dieciocho"),
        ("nineteen", "diecinueve"),
        ("twenty", "veinte"),
        ("thirty", "treinta"),
        ("forty", "cuarenta"),
        ("fifty", "cincuenta"),
        ("sixty", "sesenta"),
        ("seventy", "setenta"),
        ("eighty", "ochenta"),
        ("ninety", "noventa"),
        ("one hundred", "cien"),
        ("twenty-one", "veintiuno"),
        ("twenty-two", "veintidós"),
        ("thirty-three", "treinta y tres"),
        ("thirty-four", "treinta y cuatro"),
        ("forty-four", "cuarenta y cuatro"),
        ("forty-five", "cuarenta y cinco"),
        ("fifty-six", "cincuenta y seis"),
        ("fifty-seven", "cincuenta y siete"),
        ("sixty-eight", "sesenta y ocho"),
        ("seventy-seven", "setenta y siete"),
        ("eighty-eight", "ochenta y ocho"),
        ("ninety-three", "noventa y tres"),
    ],

    "Preguntar (Questions)": [
        ("How are (things)?", "¿Qué tal?"),
        ("How are you?", "¿Cómo estás?"),
        ("All good?", "¿Todo bien?"),
        ("How is everything?", "¿Qué tal todo?"),
        ("How's it going (for you)?", "¿Qué tal te va?"),
        ("What's up?", "¿Qué hay?"),
        ("What are you up to?", "¿Qué te cuentas?"),
        ("How is (he/she)?", "¿Cómo está?"),
        ("How are you? (formal)", "¿Cómo se encuentra?"),
        ("How are you? (formal, alt.)", "¿Cómo le va?"),
    ],

    "Responses": [
        ("very well", "muy bien"),
        ("well", "bien"),
        ("great", "genial"),
        ("all good", "todo bien"),
        ("everything great", "todo genial"),
        ("well...", "bueno..."),
        ("getting by", "tirando"),
        ("so-so, and you?", "regular, ¿y tú?"),
        ("not very well", "no muy bien"),
        ("bad", "mal"),
        ("awful", "fatal"),
    ],

    "Saludar (Greetings)": [
        ("hello", "hola"),
        ("hi / hello (neutral)", "buenas"),
        ("good morning", "buenos días"),
        ("good afternoon", "buenas tardes"),
        ("long time no see!", "¡cuánto tiempo!"),
        ("I'm glad to see you", "me alegro de verte"),
        ("nice to see you", "qué gusto verte"),
        ("so happy to see you", "qué alegría verte"),
    ],

    "Despedirse (Goodbyes)": [
        ("goodbye", "adiós"),
        ("see you soon", "hasta pronto"),
        ("good night", "buenas noches"),
        ("see you later", "hasta luego"),
        ("see you tomorrow", "hasta mañana"),
        ("bye", "chao"),
        ("see you", "hasta la vista"),
        ("see you Monday/Tuesday", "hasta el lunes / martes"),
        ("see you another time", "hasta otra"),
        ("see you (soon)", "nos vemos (pronto)"),
        ("hope it goes well!", "¡que vaya bien!"),
    ],

    "Dialogue": [
        ("Naomi and Pedro", "Naomi y Pedro"),
        ("My name is David. Nice to meet you.", "Me llamo David. Mucho gusto."),
        ("Pleased to meet you (fem.)", "Encantada."),
        ("Fine, a little tired.", "Bien, un poco cansada."),
        ("Sleep well / rest up.", "Que descanses."),
        ("Likewise, see you tomorrow.", "Igualmente, hasta mañana."),
        ("this girl", "esta chica"),
        ("this boy", "este chico"),
        ("My name is Lucas and I am French. I am thirty-one and I am a nurse", "me llamo Lucas y soy francés. Tengo treinta y uno y soy enfermero"),
        ("His name is Lucas and he is French. He is thirty-one years old and he is a nurse", "él se llama Lucas y es francés. Tiene treinta y uno años y es enfermero"),
        ("I am in Madrid", "estoy en Madrid"),
        ("Where are you from?", "¿De dónde eres?"),
        ("How interesting!", "¡Qué interesante!"),
        ("Yes, me too. Hey, what are you doing this afternoon?", "Sí, yo también. Oye, ¿qué haces esta tarde?"),
        ("Nothing special. And you?", "Nada especial. ¿Y tú?"),
        ("I have Spanish class.", "Tengo clase de español."),
        ("Okay, I'm off now.", "Bueno, me voy ya."),
        ("Goodbye, have a good day.", "Adiós, que tengas un buen día."),
        ("Thanks, likewise.", "Gracias, igualmente."),
    ],

    "Classroom Objects": [
        ("pen", "bolígrafo"),
        ("pencil", "lápiz"),
        ("laptop", "portátil"),
        ("chair", "silla"),
        ("projector", "proyector"),
        ("whiteboard", "pizarra blanca"),
        ("tablet", "tableta"),
        ("pencil case", "estuche"),
        ("table / desk", "mesa"),
        ("book", "libro"),
        ("notebook", "cuaderno"),
        ("sheet of paper", "hoja de papel"),
        ("backpack", "mochila"),
        ("computer (alt.)", "ordenador"),
        ("ruler", "regla"),
        ("scissors", "tijeras"),
        ("calculator", "calculadora"),
        ("eraser", "borrador"),
        ("sharpener", "sacapuntas"),
        ("camera", "cámara de fotos"),
        ("also / too", "también"),
    ],

    "Grammar (Tener & Plurals)": [
        ("I have three coins", "yo tengo tres monedas"),
        ("I have four things", "yo tengo cuatro cosas"),
        ("I have a pen", "yo tengo un bolígrafo"),
        ("I have a laptop", "yo tengo un portátil"),
        ("I have a table", "yo tengo una mesa"),
        ("I don’t have the books", "yo no tengo los libros"),
        ("I don’t have a glass of water", "yo no tengo un vaso de agua"),
        ("I don’t have the glasses", "yo no tengo las gafas"),
        ("plural of lápiz", "lápices"),
        ("plural of silla", "sillas"),
        ("plural of portátil", "portátiles"),
        ("plural of hoja de papel", "hojas de papel"),
        ("the ball", "el balón"),
        ("the balls", "los balones"),
        ("the plant", "la planta"),
        ("the plants", "las plantas"),
    ],

    "Requests & Needs": [
        ("I like to draw with a pencil", "me gusta dibujar con un lápiz"),
        ("Can you lend me a blue pen?", "¿me dejas un boli azul?"),
        ("I have a yellow highlighter", "tengo un subrayador amarillo"),
        ("This pencil has no tip", "este lápiz no tiene punta"),
        ("I need a sharpener", "¡necesito un sacapuntas!"),
        ("Can you lend me your eraser?", "¿me prestas tu borrador?"),
        ("I have to look for a house", "tengo que buscar una casa"),
        ("In maths class we use calculators", "en clase de matemáticas utilizamos calculadoras"),
        ("I keep all my things in my backpack", "guardo todas mis cosas en mi mochila"),
        ("In my notebook I write with a pen", "en mi cuaderno escribo con bolígrafo"),
        ("The teacher writes on the board", "la profesora escribe en la pizarra"),
        ("A pair of glasses", "un par de gafas"),
        ("With a ruler you can make straight lines", "con la regla puedes hacer líneas rectas"),
    ],

    "Feelings & Concepts": [
        ("sun", "sol"),
        ("star", "estrella"),
        ("dawn", "alborada"),
        ("trust / confidence", "confianza"),
        ("bat (animal)", "murciélago"),
        ("we dance", "bailamos"),
        ("thank you", "gracias"),
        ("feeling", "sentimiento"),
        ("solidarity", "la solidaridad"),
        ("mother", "madre"),
        ("joy / happiness", "alegría"),
        ("lawyer", "abogado"),
        ("football / soccer", "fútbol"),
        ("I desire love", "deseo amor"),
        ("to love / to want", "querer"),
        ("male / macho", "macho"),
        ("researcher / investigator", "investigador"),
        ("beauty", "belleza"),
        ("you (informal)", "tú"),
        ("affection / darling", "cariño"),
        ("mellifluous / sweet-sounding", "melíflua"),
        ("I am sleepy", "yo tengo sueño"),
        ("I have a dream", "yo tengo un sueño"),
    ],

    "Virtues & Abstract Words": [
        ("truth", "verdad"),
        ("loyalty", "lealtad"),
        ("confidence", "confianza"),
        ("spirit", "espíritu"),
        ("love", "amor"),
    ],

    "Miscellaneous": [
        ("How was it? It was...", "¿Cómo fue? Fue..."),
        ("It was easy / difficult / so-so / more or less", "fue fácil / difícil / así así / más o menos"),
        ("the mountain peak", "la punta de la montaña"),
        ("I need food", "necesito comida"),
        ("I need a cup of wine", "necesito una copa de vino"),
        ("Do you have anything?", "¿tienes algo?"),
        ("You have nothing", "no tienes nada"),
        ("other languages", "otras lenguas"),
        ("come se escribe __ en español", "¿cómo se escribe __ en español?"),
        ("how do you pronounce 'pizarra'?", "¿cómo se pronuncia 'pizarra'?"),
    ],

    "Common Verbs & Phrases": [
        ("to leave / to let", "dejar"),
        ("I leave / I let", "dejo"),
        ("I leave you a pencil", "te dejo un lápiz"),
        ("to take / to drink", "tomar"),
        ("take (here you go)", "toma"),
        ("to work", "trabajar"),
        ("to sing", "cantar"),
        ("to eat", "comer"),
        ("to live", "vivir"),
        ("languages", "idiomas"),
        ("él trabaja __ camarero", "de"),
        ("trabaja __ __ restaurante", "en un"),
        ("all verbs end in?", "ar, er, ir"),
        ("idiomas", "languages"),
        ("however", "sin embargo"),
        ("additionally", "además"),
        ("extroverted", "extrovertidos"),
    ],

    "Math & Quantities": [
        ("more", "más"),
        ("less / minus", "menos"),
        ("nine plus one equals ten", "nueve más uno = diez"),
    ],

    "Nationalities & Countries": [
        ("Canadian", "canadiense"),
        ("He is French", "es francés"),
        ("She is French", "es francesa"),
        ("He is Italian", "es italiano"),
        ("She is Italian", "es italiana"),
        ("American / from the U.S.", "estadounidense"),
        ("Scottish (fem.)", "escocesa"),
        ("Belgian", "belga"),
        ("England", "Inglaterra"),
        ("Spain", "España"),
        ("Switzerland", "Suiza"),
        ("Chile", "Chile"),
        ("Norway", "Noruega"),
        ("Sweden", "Suecia"),
        ("Algeria", "Argelia"),
        ("Russian (fem.)", "rusa"),
        ("Russian (masc.)", "ruso"),
        ("Denmark", "Dinamarca"),
        ("Panamanian", "panameño"),
        ("Venezuelan", "venezolano"),
        ("Cuban", "cubano"),
        ("Chilean", "chileno"),
        ("Peruvian", "peruano"),
        ("Ecuadorian", "ecuatoriano"),
        ("Argentine / Argentinian", "argentino"),
        ("Maltese (masc.)", "maltés"),
        ("Maltese (fem.)", "maltesa"),
        ("Poland", "Polonia"),
        ("Polish (masc.)", "polaco"),
        ("Lithuanian (masc.)", "lituano"),
        ("Lithuanian (fem.)", "lituana"),
        ("Indonesian (fem.)", "indonesia"),
        ("Indonesian (masc.)", "indonesio"),
        ("Irish", "irlandés"),
        ("In pairs, think of four things and write the nationality you associate with each one",
         "En parejas, pensad cuatro cosas y escribid la nacionalidad con la que relacionáis cada una."),
        ("Greek (masc.)", "griego"),
        ("Greek (fem.)", "griega"),
        ("Dutch (masc.)", "holandés"),
        ("Dutch (fem.)", "holandesa"),
        ("Belgium", "Bélgica"),
        ("Ukrainian (fem.)", "ucraniana"),
        ("Ukraine", "Ucrania"),
        ("I am Ukrainian", "soy ucraniana"),
        ("I am from Ukraine", "soy de Ucrania"),
        ("My name is Antonio, I am from Peru", "me llamo Antonio, soy de Perú"),
        ("My name is Jacob, I am Belgian", "me llamo Jacob, soy belga"),
        ("My name is John, I am British, I am from the United Kingdom", "me llamo John, soy británico, soy del Reino Unido"),
    ],

    "Professions": [
        ("pronunciation", "pronunciación"),
        ("painter (masc.)", "pintor"),
        ("painter (fem.)", "pintora"),
        ("writer (masc.)", "escritor"),
        ("writer (fem.)", "escritora"),
        ("teacher (masc.)", "profesor"),
        ("teacher (fem.)", "profesora"),
        ("scientist (fem.)", "científica"),
        ("student", "estudiante"),
        ("journalist", "periodista"),
        ("salesperson / commercial agent", "comercial"),
        ("driver / chauffeur", "chófer"),
        ("agent", "agente"),
        ("police officer", "policía"),
        ("model", "modelo"),
        ("fashion designer", "diseñador/a de moda"),
        ("librarian (masc.)", "bibliotecario"),
        ("librarian (fem.)", "bibliotecaria"),
        ("employee (masc.)", "empleado"),
        ("employee (fem.)", "empleada"),
        ("waiter", "camarero"),
        ("waitress", "camarera"),
        ("hairdresser (masc.)", "peluquero"),
        ("hairdresser (fem.)", "peluquera"),
        ("doctor (masc.)", "doctor"),
        ("doctor (fem.)", "doctora"),
        ("translator", "traductor"),
        ("nurse (masc.)", "enfermero"),
        ("engineer (masc.)", "ingeniero"),
        ("engineer (fem.)", "ingeniera"),
        ("lawyer (masc.)", "abogado"),
        ("lawyer (fem.)", "abogada"),
        ("architect (fem.)", "arquitecta"),
        ("architect (masc.)", "arquitecto"),
        ("editor (masc.)", "editor"),
        ("editor (fem.)", "editora"),
        ("bookstore", "librería"),
        ("shop assistant", "dependiente"),
        ("vendor / seller", "vendedor"),
        ("occupational therapist", "terapeuta ocupacional"),
        ("systems engineer", "ingeniero de sistemas"),
        ("dentist", "dentista"),
        ("homemaker", "ama de casa"),
        ("midwife", "matrona"),
        ("father", "padre"),
        ("carpenter", "tablador"),
        ("artist", "artista"),
        ("counsellor", "consejero"),
        ("accountant", "contador"),
        ("quantitative analyst (masc.)", "analista cuantitativo"),
        ("quantitative analyst (fem.)", "analista cuantitativa"),
        ("waitress", "camarera"),
        ("hospital", "hospital"),
        ("shop assistant", "dependiente"),
        ("shop / store", "tienda"),
        ("scientist (fem.)", "científica"),
        ("laboratory", "laboratorio"),
        ("receptionist", "recepcionista"),
        ("language school", "escuela de idiomas"),
        ("She works as a waitress and works in a hospital", "trabaja de camarera y trabaja en un hospital"),
        ("He works as a shop assistant and works in a store", "trabaja de dependiente y trabaja en una tienda"),
        ("She works as a scientist and works in a laboratory", "trabaja de científica y trabaja en un laboratorio"),
        ("He works as a receptionist and works in a language school", "trabaja de recepcionista y trabaja en una escuela de idiomas"),
        ("judge (masc.)", "juez"),
        ("judge (fem.)", "jueza"),
        ("secretary (masc.)", "secretario"),
        ("secretary (fem.)", "secretaria"),
        ("thief (masc.)", "ladrón"),
        ("thief (fem.)", "ladrona"),
        ("My friend Carl is a nurse and works at his patients' house", "mi amigo Carl es enfermero y trabaja en una casa de sus pacientes"),
        ("My friend Alex is a software engineer and works in an office", "mi amigo Alex es ingeniero de software y trabaja en una oficina"),
        ("My friend Ross is in business and works from home", "mi amigo Ross está en el negocio y trabaja desde casa"),
    ],

    "Food & Culture": [
        ("The tango is Argentine", "el tango es argentino"),
        ("Sushi is Japanese", "el sushi es japonés"),
        ("Pizza is Italian", "la pizza es italiana"),
        ("Flamenco is Spanish", "el flamenco es español"),
        ("The balalaika is Russian", "la balalaika es rusa"),
        ("The croissant is French", "el cruasán es francés"),
        ("The baguette is French", "la baguette es francesa"),
        ("Big Ben is British", "el Big Ben es británico"),
        ("Big Ben is English", "el Big Ben es inglés"),
        ("Paella is Spanish", "la paella es española"),
        ("The city is Chinese", "la ciudad es china"),
        ("Curry is Indian", "el curry es indio"),
        ("The hamburger is American", "la hamburguesa es estadounidense"),
        ("From which country do these things come?", "¿De qué país proceden estas cosas?"),
        ("Write in your notebook the nationality that corresponds to them",
         "Escribe en tu cuaderno la nacionalidad que les corresponde"),
        ("Be careful with gender!", "¡Cuidado con el género!"),
    ],

    "Grammar (Articles & Gender)": [
        ("to the (abbreviation)", "al (a + el)"),
        ("from the (abbreviation)", "del (de + el)"),
        ("some (masculine)", "unos"),
        ("some (feminine)", "unas"),
        ("determined / definite", "determinados"),
        ("undetermined / indefinite", "indeterminados"),
        ("some pens", "unos bolígrafos"),
        ("some tables", "unas mesas"),
    ],

    "Pronunciation Practice": [
        ("pronunciation pattern: gi", "gi"),
        ("pronunciation pattern: ge", "ge"),
        ("pronunciation pattern: ga", "ga"),
        ("pronunciation pattern: go", "go"),
        ("pronunciation pattern: gu", "gu"),
        ("pronunciation pattern: gue", "gue"),
        ("pronunciation pattern: gui", "gui"),
        ("cook / chef", "cocinero"),
    ],

    "Mini Dialogues": [
        ("What", "qué"),
        ("Where", "dónde"),
        ("What do you do for a living?", "¿A qué te dedicas?"),
        ("What do you do for a living? (formal)", "¿A qué se dedica usted?"),
        ("¿a qué te dedicas?", "What do you do for a living?"),
        ("¿a qué se dedica?", "What do you do for a living? (formal)"),
        ("What is your name?", "¿cómo te llamas?"),
        ("What is your name? (formal)", "¿cuál es su nombre?"),
        ("How old are you?", "¿cuántos años tienes?"),
        ("How old are you? (formal)", "¿cuántos años tiene?"),
        ("I am 23 years old", "tengo 23 años"),
        ("What is your email?", "¿cuál es tu correo electrónico?"),
        ("Do you have email?", "¿tienes correo electrónico?"),
        ("Do you have email? (formal)", "¿tiene correo electrónico?"),
        ("What do you work in?", "¿en qué trabajas?"),
        ("What do you work in? (formal)", "¿en qué trabaja?"),
        ("¿en qué trabajas?", "What do you work in?"),
        ("¿en qué trabajo?", "What do I work in?"),
        ("I know", "conozco"),
        ("Then / so / in that case", "entonces"),
        ("Are you the new colleague?", "¿Tú eres el nuevo compañero?"),
        ("Do you work here at the centre or from home?", "¿Trabajas aquí en el centro o desde casa?"),
        ("Hello, my name is Andrés. I’m Argentine and a Spanish teacher. I’m 35 years old.",
         "Hola, mi nombre es Andrés. Soy argentino y soy profesor de español. Tengo 35 años."),
        ("Hello, my name is John. I work as a systems engineer and I’m English. I’m 33 years old.",
         "Hola, mi nombre es John. Trabajo de ingeniero de sistemas y soy inglés. Tengo 33 años."),
        ("Maha works in a workshop.", "Maha en un taller."),
        ("Chloe works at a TV channel.", "Chloe en un canal de televisión."),
        ("Ulrich works in a language school.", "Ulrich en una escuela de lenguas."),
        ("Gibson works in a laboratory.", "Gibson en un laboratorio."),
        ("Andrés works at a university.", "Andrés en una universidad."),
        ("name", "nombre"),
        ("nationality", "nacionalidad"),
        ("profession", "profesión"),
        ("age", "edad"),
        ("name", "nombre"),
        ("surname / last name", "apellido"),
        ("What is your last name?", "¿cuál es su apellido?"),
        ("@ symbol", "arroba"),
    ],
    "Alphabet & Pronunciation": [
        ("A", "a — pronounced 'ah'"),
        ("B", "be — pronounced 'beh'"),
        ("C", "ce — before e or i, sounds like 'th' in Spain or 's' in Latin America"),
        ("Ch", "che — pronounced 'cheh'"),
        ("D", "de — pronounced 'deh'"),
        ("E", "e — pronounced 'eh'"),
        ("F", "efe — pronounced 'eh-feh'"),
        ("G", "ge — before e or i, like English 'h'; otherwise hard 'g'"),
        ("H", "hache — silent letter"),
        ("I", "i — pronounced 'ee'"),
        ("J", "jota — like English 'h' in hello"),
        ("K", "ka — pronounced 'kah'"),
        ("L", "ele — pronounced 'eh-leh'"),
        ("LL", "elle — pronounced 'ye' or 'zh' depending on region"),
        ("M", "eme — pronounced 'eh-meh'"),
        ("N", "ene — pronounced 'eh-neh'"),
        ("Ñ", "eñe — pronounced 'enye', like 'ny' in canyon"),
        ("O", "o — pronounced 'oh'"),
        ("P", "pe — pronounced 'peh'"),
        ("Q", "cu — pronounced 'koo' (always followed by 'u')"),
        ("R", "ere — single r, soft roll"),
        ("RR", "erre — rolled or trilled r"),
        ("S", "ese — pronounced 'eh-seh'"),
        ("T", "te — pronounced 'teh'"),
        ("U", "u — pronounced 'oo'"),
        ("V", "uve — almost like 'b', pronounced 'oo-beh'"),
        ("W", "uve doble — pronounced 'oo-beh doble' or 'doble ve'"),
        ("X", "equis — pronounced 'eh-kees'"),
        ("Y", "i griega — pronounced 'ee gree-eh-gah' or 'ye'"),
        ("Z", "zeta — 'th' in Spain, 's' in Latin America"),
    ],
    "Days of the Week": [
        ("Monday", "lunes"),
        ("Tuesday", "martes"),
        ("Wednesday", "miércoles"),
        ("Thursday", "jueves"),
        ("Friday", "viernes"),
        ("Saturday", "sábado"),
        ("Sunday", "domingo"),
        ("the week", "la semana"),
        ("the weekend", "el fin de semana"),
        ("today", "hoy"),
        ("tomorrow", "mañana"),
        ("yesterday", "ayer"),
        ("What day is it today?", "¿Qué día es hoy?"),
        ("It’s Monday", "Es lunes"),
        ("See you on Monday", "Hasta el lunes"),
        ],
}
