decks = {
    "Phrases": [
        ("the morning", "la mañana"),
        ("from where", "de dónde"),
        ("What are you doing this afternoon?", "¿Qué haces esta tarde?"),
        ("to review / revise", "repasar"),
        ("What do you mean, why?", "¿Qué por qué?"),
        ("What day is it today?", "¿Qué día es hoy?"),
        ("clear as water", "clara como el agua"),
        ("Sorry, I don't know", "Lo siento, no lo sé"),
        ("Sorry, I don't speak Japanese", "Lo siento, no hablo japonés"),
        ("Sorry, I speak a bit of Spanish", "Lo siento, hablo un poco de español"),
        ("What does it mean?", "¿Qué significa?"),
        ("Hey, this afternoon I was thinking that you could go to the beach", "Mira, esta tarde estaba pensando que podrías ir a la playa"),
        ("I see a movie", "Yo veo una película"),
        ("I listen", "Yo escucho"),
        ("I read a novel / You read a book", "Yo leo una novela / Tú lees un libro"),
        ("You write a diary", "Tú escribes un diario"),
        ("We write exercises", "Nosotros escribimos ejercicios"),
        ("They practice pronunciation", "Ellas practican la pronunciación"),
        ("She does exercises", "Ella hace ejercicios"),
        ("You all do an exchange", "Vosotros hacéis un intercambio"),
        ("I take a Spanish course", "Yo hago un curso de español"),
        ("What do you want to do tomorrow?", "¿Qué quieres hacer mañana?"),
        ("What do you want to do on your vacation?", "¿Qué quieres hacer en tus vacaciones?"),
        ("What do you want to learn this year?", "¿Qué quieres aprender este año?"),
        ("What don't you want to do this week?", "¿Qué no quieres hacer esta semana?"),
        ("Tomorrow I want to...", "Mañana quiero..."),
        ("On my vacation I want to...", "En mis vacaciones quiero..."),
        ("This year I want to learn...", "Este año quiero aprender..."),
        ("This week I don't want to...", "Esta semana no quiero..."),
        ("Are you multilingual?", "¿Eres plurilingüe?"),
        ("We say that a person is multilingual when they communicate in more than one language", "Decimos que una persona es plurilingüe cuando se comunica en más de una lengua"),
        ("to travel (for tourism or for work)", "viajar (por turismo o por trabajo)"),
        ("to watch series or movies from countries all over the world", "ver series o películas de países de todo el mundo"),
        ("to read and write on social networks", "leer y escribir en redes sociales"),
        ("to have colleagues from different nationalities", "tener compañeros y compañeras de trabajo de diferentes nacionalidades"),
        ("to study in another country", "estudiar en otro país"),
        ("in my Spanish", "en mi español"),
        ("for tourism", "por turismo"),
        ("sweet inn", "dulce posada"),
        ("each", "cada"),
        ("all over the world", "de todo el mundo"),
        ("social networks", "redes sociales"),
        ("speak", "hablar - 'talu' pronunciation note"),
        ("study", "estudiar - linda"),
        ("work", "trabajar"),
        ("cook", "cocinar"),
        ("to have", "tener"),
        ("can/be able to", "poder"),
        ("go out/go out for fun", "salir"),
        ("to fly", "volar"),
        ("to feel", "sentir"),
        ("want/love", "querer - conjugated as quiero/quieres"),
        ("to be (location/state)", "estar"),
        ("to see", "ver"),
        ("to do/make", "hacer"),
        ("exchange", "intercambio"),
        ("gym exercises or study exercises", "ejercicios"),
        ("Where are you now?", "dónde estás ahora"),
        ("My city is neither small nor big", "mi ciudad no es ni pequeña ni grande"),
        ("How are you today?", "cómo estás hoy?"),
        ("What is your profession or job?", "cuál es tu profesión o trabajo?"),
        ("Is your city big or small?", "tu ciudad es grande o pequeña"),
        ("Are you tired or energetic?", "estás cansado/a o con energía?"),
        ("Is your house near or far from the center?", "tu casa está cerca o lejos del centro"),
        ("My house is far from the center", "mi casa está lejos del centro"),
        ("I'm from Colchester", "Soy de Colchester"),
        ("Do you want to go to the cinema with me?", "quieres ir al cine conmigo?"),
        ("Okay! What movie do you want to see?", "vale! qué película quieres ver?"),
        ("This weekend I want to go out with my Spanish friends", "este fin de semana quiero salir con mis amigos españoles"),
        ("What a good idea!", "qué buena idea!"),
        ("What do you want to do tomorrow night?", "qué quieres hacer mañana por la noche?"),
        ("I want to go out to dinner and then to the disco", "quiero salir a cenar y después a la discoteca"),
        ("I want to learn another language", "quiero aprender otro idioma"),
        ("Oh really? Which one?", "ah, sí? cuál?"),
        ("Mercedes and I want to go to Rosalia's concert. Do you want to go with us?", "Mercedes y yo queremos ir a concierto de Rosalia. quieres ir con nosotras?"),
        ("Yes, of course", "sí, claro"),
        ("Do you have plans for this weekend?", "tienes planes para esta fin de semana?"),
        ("Yes, Eduardo and I want to go on an excursion", "sí, Eduardo y yo queremos ir de excursión"),
        ("because I want to eat...", "porque quiero comer..."),
        ("I want to eat...", "Quiero comer..."),
        ("I want to visit...", "quiero visitar..."),
        ("I want to see...", "quiero ver..."),
        ("I want to practice...", "quiero practicar..."),
        ("for the food", "por la comida"),
        ("for the dancing", "por el baile"),
        ("for the people", "por la gente"),
        ("I cook turkey meatballs", "Yo cocino albóndigas de pavo"),
        ("residence", "lugar de residencia"),
        ("languages that he/she speaks", "lenguas que habla"),
        ("why he/she studies Spanish", "por qué estudia español"),
        ("what things he/she does to learn Spanish", "qué cosas hace para aprender español"),
        ("plans for the future", "planes para el futuro"),
        ("learning", "aprendiendo"),
        ("mainly", "principalmente"),
        ("my native language", "mi lengua materna"),
        ("I speak with natives", "hablo con los nativos"),
        ("Every Wednesday, after class, I go home to sleep", "Cada miércoles, después de la clase, voy a casa a dormir"),
        ("Every Wednesday, after class, I go home to eat", "Cada miércoles, después de la clase, voy a casa a comer"),
        ("Do you know these festivals?", "tu conoces estas fiestas?"),
        ("the shopping", "la compra"),
        ("cake", "pastel"),
        ("I go with my friends to the restaurant to celebrate my birthday", "voy con mis amigos al restaurante para celebrar mi cumpleaños"),
        ("I study Spanish to travel to Spain on vacation", "yo estudio español para viajar a España en las vacaciones"),
        ("of course, I'm going because I want to celebrate your birthday", "por supuesto, voy porque quiero celebrar tu cumpleaños"),
        ("of course", "por supuesto"),
        ("for how long", "por cuanto tiempo"),
        ("birthday", "cumpleaños"),
        ("to turn/complete (years)", "cumplir"),
        ("I work in the mornings", "trabajo por las mañanas"),
        ("tomorrow I have a Spanish meetup", "mañana yo tengo una Spanish meetup"),
        ("tomorrow, in the morning, I have a class", "mañana, por la mañana, yo tengo una clase"),
        ("this gift is for you", "este regalo es para ti"),
        ("I study Spanish because I like it", "estudio español porque me gusta"),
        ("I'm going to walk through the park", "voy a caminar por el parque"),
        ("why do you want to learn more vocabulary?", "¿por qué quieres aprender más vocabulario?"),
        ("to travel to Mexico I need to practice more", "para viajar a México necesito practicar más"),
        ("I'm not going to class because I'm sick", "no voy a clase porque estoy enfermo"),
        ("every day", "cada día"),
        ("to have fun", "divertirte"),
        ("It's important to leave early", "Es importante salir temprano"),
        ("Spanish songs", "canciones de español"),
    ],

    "Verb Conjugations": [
        ("My name", "Me llamo (yo)"),
        ("Your name", "Te llamas (tú)"),
        ("His/Her name", "Se llama (él / ella)"),
        ("Their names", "Se llaman (ellos / ellas)"),
        ("Our names", "Nos llamamos (nosotros)"),
        ("You all names", "Os llamáis (vosotros)"),
        ("Formal your name", "Se llama (usted)"),
        ("(yo) como", "I eat"),
        ("yo como una manzana", "I eat an apple"),
        ("(tú) comes", "you eat"),
        ("tú comes pan", "you eat bread"),
        ("(él) come", "he eats"),
        ("él come arroz", "he eats rice"),
        ("(ella) come", "she eats"),
        ("ella come arroz", "she eats rice"),
        ("(usted) come", "you eat (formal)"),
        ("usted come arroz", "you eat rice (formal)"),
        ("(nosotros) comemos", "we eat"),
        ("nosotros comemos juntos", "we eat together"),
        ("(vosotros) coméis", "you all eat"),
        ("vosotros coméis tarde", "you all eat late"),
        ("(ellos) comen", "they eat (masc.)"),
        ("ellos comen en casa", "they eat at home (masc.)"),
        ("(ellas) comen", "they eat (fem.)"),
        ("ellas comen en casa", "they eat at home (fem.)"),
        ("(ustedes) comen", "you all eat (formal)"),
        ("ustedes comen en casa", "you all eat at home (formal)"),
        ("(yo) vivo", "I live"),
        ("yo vivo en Londres", "I live in London"),
        ("(tú) vives", "you live"),
        ("tú vives cerca", "you live nearby"),
        ("(él) vive", "he lives"),
        ("él vive solo", "he lives alone"),
        ("(ella) vive", "she lives"),
        ("ella vive sola", "she lives alone"),
        ("(usted) vive", "you live (formal)"),
        ("usted vive en Madrid", "you live in Madrid (formal)"),
        ("(nosotros) vivimos", "we live"),
        ("nosotros vivimos aquí", "we live here"),
        ("(vosotros) vivís", "you all live"),
        ("vosotros vivís lejos", "you all live far away"),
        ("(ellos) viven", "they live (masc.)"),
        ("ellos viven juntos", "they live together (masc.)"),
        ("(ellas) viven", "they live (fem.)"),
        ("ellas viven juntas", "they live together (fem.)"),
        ("(ustedes) viven", "you all live (formal)"),
        ("ustedes viven aquí", "you all live here (formal)"),
        ("(yo) trabajo", "I work"),
        ("yo trabajo mucho", "I work a lot"),
        ("(tú) trabajas", "you work"),
        ("tú trabajas en casa", "you work at home"),
        ("(él) trabaja", "he works"),
        ("él trabaja de camarero", "he works as a waiter"),
        ("(ella) trabaja", "she works"),
        ("ella trabaja de camarera", "she works as a waitress"),
        ("(usted) trabaja", "you work (formal)"),
        ("usted trabaja en una oficina", "you work in an office (formal)"),
        ("(nosotros) trabajamos", "we work"),
        ("nosotros trabajamos en un banco", "we work in a bank"),
        ("(vosotros) trabajáis", "you all work"),
        ("vosotros trabajáis poco", "you all work little"),
        ("(ellos) trabajan", "they work (masc.)"),
        ("ellos trabajan juntos", "they work together (masc.)"),
        ("(ellas) trabajan", "they work (fem.)"),
        ("ellas trabajan juntas", "they work together (fem.)"),
        ("(ustedes) trabajan", "you all work (formal)"),
        ("ustedes trabajan en una empresa", "you all work in a company (formal)"),
        ("(yo) canto", "I sing"),
        ("yo canto bien", "I sing well"),
        ("(tú) cantas", "you sing"),
        ("tú cantas en la ducha", "you sing in the shower"),
        ("(él) canta", "he sings"),
        ("él canta muy bonito", "he sings very beautifully"),
        ("(ella) canta", "she sings"),
        ("ella canta muy bonito", "she sings very beautifully"),
        ("(usted) canta", "you sing (formal)"),
        ("usted canta en el coro", "you sing in the choir (formal)"),
        ("(nosotros) cantamos", "we sing"),
        ("nosotros cantamos una canción", "we sing a song"),
        ("(vosotros) cantáis", "you all sing"),
        ("vosotros cantáis juntos", "you all sing together"),
        ("(ellos) cantan", "they sing (masc.)"),
        ("ellos cantan en un coro", "they sing in a choir (masc.)"),
        ("(ellas) cantan", "they sing (fem.)"),
        ("ellas cantan en un coro", "they sing in a choir (fem.)"),
        ("(ustedes) cantan", "you all sing (formal)"),
        ("ustedes cantan muy bien", "you all sing very well (formal)"),
        ("to be (location/state)", "estar"),
        ("to be (identity/characteristics)", "ser"),
        ("(yo) estoy", "I am"),
        ("yo estoy cansado", "I am tired"),
        ("(tú) estás", "you are"),
        ("tú estás feliz", "you are happy"),
        ("(él) está", "he is"),
        ("él está en casa", "he is at home"),
        ("(ella) está", "she is"),
        ("ella está en la escuela", "she is at school"),
        ("(usted) está", "you are (formal)"),
        ("usted está en la oficina", "you are in the office (formal)"),
        ("(nosotros) estamos", "we are (masc.)"),
        ("nosotros estamos en el parque", "we are in the park (masc.)"),
        ("(nosotras) estamos", "we are (fem.)"),
        ("nosotras estamos en el parque", "we are in the park (fem.)"),
        ("(vosotros) estáis", "you all are (masc.)"),
        ("vosotros estáis listos", "you all are ready (masc.)"),
        ("(vosotras) estáis", "you all are (fem.)"),
        ("vosotras estáis cansadas", "you all are tired (fem.)"),
        ("(ellos) están", "they are (masc.)"),
        ("ellos están ocupados", "they are busy (masc.)"),
        ("(ellas) están", "they are (fem.)"),
        ("ellas están contentas", "they are happy (fem.)"),
        ("(ustedes) están", "you all are (formal)"),
        ("ustedes están aquí", "you all are here (formal)"),
        ("(yo) soy", "I am"),
        ("yo soy estudiante", "I am a student"),
        ("(tú) eres", "you are"),
        ("tú eres simpático", "you are nice"),
        ("(él) es", "he is"),
        ("él es profesor", "he is a teacher"),
        ("(ella) es", "she is"),
        ("ella es médica", "she is a doctor"),
        ("(usted) es", "you are (formal)"),
        ("usted es muy amable", "you are very kind (formal)"),
        ("(nosotros) somos", "we are (masc.)"),
        ("nosotros somos amigos", "we are friends (masc.)"),
        ("(nosotras) somos", "we are (fem.)"),
        ("nosotras somos amigas", "we are friends (fem.)"),
        ("(vosotros) sois", "you all are (masc.)"),
        ("vosotros sois españoles", "you all are Spanish (masc.)"),
        ("(vosotras) sois", "you all are (fem.)"),
        ("vosotras sois españolas", "you all are Spanish (fem.)"),
        ("(ellos) son", "they are (masc.)"),
        ("ellos son ingenieros", "they are engineers (masc.)"),
        ("(ellas) son", "they are (fem.)"),
        ("ellas son enfermeras", "they are nurses (fem.)"),
        ("(ustedes) son", "you all are (formal)"),
        ("ustedes son de México", "you all are from Mexico (formal)"),
        ("The books are in the library", "los libros están en la biblioteca"),
        ("We are concentrated", "nosotros estamos concentrados"),
        ("Are you busy?", "¿está usted ocupado?"),
        ("No, I am not busy", "no, (yo) no estoy ocupado"),
        ("You all are concentrated", "vosotros estáis concentrados"),
        ("to have", "tener"),
        ("(yo) tengo", "I have"),
        ("yo tengo un coche", "I have a car"),
        ("(tú) tienes", "you have"),
        ("tú tienes una casa", "you have a house"),
        ("(él) tiene", "he has"),
        ("él tiene un perro", "he has a dog"),
        ("(ella) tiene", "she has"),
        ("ella tiene un gato", "she has a cat"),
        ("(usted) tiene", "you have (formal)"),
        ("usted tiene una cita", "you have an appointment (formal)"),
        ("(nosotros) tenemos", "we have (masc.)"),
        ("nosotros tenemos hambre", "we are hungry (masc.)"),
        ("(nosotras) tenemos", "we have (fem.)"),
        ("nosotras tenemos hambre", "we are hungry (fem.)"),
        ("(vosotros) tenéis", "you all have (masc.)"),
        ("vosotros tenéis frío", "you all are cold (masc.)"),
        ("(vosotras) tenéis", "you all have (fem.)"),
        ("vosotras tenéis sueño", "you all are sleepy (fem.)"),
        ("(ellos) tienen", "they have (masc.)"),
        ("ellos tienen dinero", "they have money (masc.)"),
        ("(ellas) tienen", "they have (fem.)"),
        ("ellas tienen suerte", "they are lucky (fem.)"),
        ("(ustedes) tienen", "you all have (formal)"),
        ("ustedes tienen razón", "you all are right (formal)"),
        ("you call (informal, uncertain)", "vos llamás"),
        ("plural of yo", "nosotros, nosotras"),
        ("plural of tú", "vosotros, vosotras, ustedes"),
        ("plural of él/ella", "ellos, ellas"),
        ("to see", "ver"),
        ("to listen", "escuchar"),
        ("to read", "leer"),
        ("to write", "escribir"),
        ("to practice", "practicar"),
        ("to do/make (all)", "hacer (todos)"),
        ("I see", "veo"),
        ("I listen", "escucho"),
        ("I read", "leo"),
        ("I write", "escribo"),
        ("I practice", "practico"),
        ("I do/make", "hago"),
        ("to go", "ir"),
        ("I go", "voy"),
        ("you go", "vas"),
        ("he/she goes", "va"),
        ("we go", "vamos"),
        ("they go", "van"),
        ("you see (tú)", "ves"),
        ("he/she sees", "ve"),
        ("we see", "vemos"),
        ("you all see", "veis"),
        ("they see", "ven"),
        ("you do/make (tú)", "haces"),
        ("he/she does/makes", "hace"),
        ("we do/make", "hacemos"),
        ("irregular verb", "verbo irregular"),
        ("to want/to love", "querer"),
        ("I want", "yo quiero"),
        ("you want", "tú quieres"),
        ("he/she/you(formal) wants", "él/ella/usted quiere"),
        ("we want", "nosotros/as queremos"),
        ("you all want", "vosotros/as queréis"),
        ("they/you all(formal) want", "ellos/as/ustedes quieren"),
        ("to speak", "hablar"),
        ("to study", "estudiar"),
        ("to cook", "cocinar"),
        ("to drink", "beber"),
        ("to go out", "salir"),
        ("to think", "pensar"),
        ("to fly", "volar"),
        ("to enjoy", "disfrutar"),
        ("to paint", "pintar"),
        ("to pass/spend", "pasar"),
        ("to usually do", "soler"),
        ("to lose", "perder"),
        ("to know (facts)", "saber"),
        ("to feel", "sentir"),
        ("exchange", "intercambio"),
        ("exercises (gym or study)", "ejercicios"),
        ("to walk", "caminar"),
        ("I walk", "yo camino"),
        ("you walk", "tú caminas"),
        ("he/she/you(formal) walks", "él/ella/usted camina"),
        ("we walk", "nosotros/as caminamos"),
        ("you all walk", "vosotros/as camináis"),
        ("they/you all(formal) walk", "ellos/as/ustedes caminan"),
        ("to improve", "mejorar"),
        ("I improve", "yo mejoro"),
        ("you improve", "tú mejoras"),
        ("he/she/you(formal) improves", "él/ella/usted mejora"),
        ("we improve", "nosotros/as mejoramos"),
        ("you all improve", "vosotros/as mejoráis"),
        ("they/you all(formal) improve", "ellos/as/ustedes mejoran"),
        ("I read", "yo leo"),
        ("you read", "tú lees"),
        ("he/she/you(formal) reads", "él/ella/usted lee"),
        ("we read", "nosotros/as leemos"),
        ("you all read", "vosotros/as leéis"),
        ("they/you all(formal) read", "ellos/as/ustedes leen"),
        ("to do/make (irregular)", "hacer"),
        ("I do/make", "yo hago"),
        ("you do/make", "tú haces"),
        ("he/she/you(formal) does/makes", "él/ella/usted hace"),
        ("we do/make", "nosotros/as hacemos"),
        ("you all do/make", "vosotros/as hacéis"),
        ("they/you all(formal) do/make", "ellos/as/ustedes hacen"),
        ("to travel", "viajar"),
        ("I travel", "yo viajo"),
        ("you travel", "tú viajas"),
        ("he/she/you(formal) travels", "él/ella/usted viaja"),
        ("we travel", "nosotros/as viajamos"),
        ("you all travel", "vosotros/as viajáis"),
        ("they/you all(formal) travel", "ellos/as/ustedes viajan"),
        ("we can (poder conjugation)", "nosotros/as podemos"),
        ("to be able to/can", "poder"),
        ("I can", "yo puedo"),
        ("you can", "tú puedes"),
        ("he/she/you(formal) can", "él/ella/usted puede"),
        ("we can", "nosotros/as podemos"),
        ("you all can", "vosotros/as podéis"),
        ("they/you all(formal) can", "ellos/as/ustedes pueden"),
        ("to know/meet", "conocer"),
        ("I know/meet", "yo conozco"),
        ("you know/meet", "tú conoces"),
        ("he/she/you(formal) knows/meets", "él/ella/usted conoce"),
        ("we know/meet", "nosotros/as conocemos"),
        ("you all know/meet", "vosotros/as conocéis"),
        ("they/you all(formal) know/meet", "ellos/as/ustedes conocen"),
        ("to live", "vivir"),
        ("I live", "yo vivo"),
        ("you live", "tú vives"),
        ("he/she/you(formal) lives", "él/ella/usted vive"),
        ("we live", "nosotros/as vivimos"),
        ("you all live", "vosotros/as vivís"),
        ("they/you all(formal) live", "ellos/as/ustedes viven"),
        ("he/she/you(formal) will be", "él/ella/usted será"),
        ("to go out/to leave", "salir"),
        ("I go out", "yo salgo"),
        ("you go out", "tú sales"),
        ("he/she/you(formal) goes out", "él/ella/usted sale"),
        ("we go out", "nosotros/as salimos"),
        ("you all go out", "vosotros/as salís"),
        ("they/you all(formal) go out", "ellos/as/ustedes salen"),
        ("to speak (infinitive)", "hablar"),
        ("I speak", "yo hablo"),
        ("you speak (informal)", "tú hablas"),
        ("he speaks", "él habla"),
        ("she speaks", "ella habla"),
        ("you speak (formal)", "usted habla"),
        ("we speak (masc.)", "nosotros hablamos"),
        ("we speak (fem.)", "nosotras hablamos"),
        ("you all speak (informal, masc.)", "vosotros habláis"),
        ("you all speak (informal, fem.)", "vosotras habláis"),
        ("they speak (masc.)", "ellos hablan"),
        ("they speak (fem.)", "ellas hablan"),
        ("you all speak (formal)", "ustedes hablan"),
        ("to want/to love (infinitive)", "querer"),
        ("we want (fem.)", "nosotras queremos"),
        ("you all want (informal, fem.)", "vosotras queréis"),
        ("they want (fem.)", "ellas quieren"),
        ("you all want (formal)", "ustedes quieren"),
        ("to do/to make (infinitive)", "hacer"),
        ("he does/makes", "él hace"),
        ("she does/makes", "ella hace"),
        ("you do/make (formal)", "usted hace"),
        ("we do/make (fem.)", "nosotras hacemos"),
        ("you all do/make (informal, fem.)", "vosotras hacéis"),
        ("they do/make (fem.)", "ellas hacen"),
        ("you all do/make (formal)", "ustedes hacen"),
        ("to learn (infinitive)", "aprender"),
        ("I learn", "yo aprendo"),
        ("you learn", "tú aprendes"),
        ("he/she/you(formal) learns", "él/ella/usted aprende"),
        ("we learn", "nosotros/as aprendemos"),
        ("you all learn", "vosotros/as aprendéis"),
        ("they/you all(formal) learn", "ellos/as/ustedes aprenden"),
        ("to receive (infinitive)", "recibir"),
        ("I receive", "yo recibo"),
        ("you receive", "tú recibes"),
        ("he/she/you(formal) receives", "él/ella/usted recibe"),
        ("we receive", "nosotros/as recibimos"),
        ("you all receive", "vosotros/as recibís"),
        ("they/you all(formal) receive", "ellos/as/ustedes reciben"),
    ],

    "Help": [
        ("how", "cómo"),
        ("What did you say?", "¿Cómo dices?"),
        ('What does "vale" mean?', '¿Qué significa "vale"?'),
        ('How do you say "water" in Spanish?', '¿Cómo se dice "water" en español?'),
        ("How do you say this in Spanish?", "¿Cómo se dice esto en español?"),
        ("Can you speak louder, please?", "¿Puedes hablar más alto, por favor?"),
        ("Can you speak more slowly, please?", "¿Puedes hablar más despacio, por favor?"),
        ("Can you repeat, please?", "¿Puedes repetir, por favor?"),
        ("to be able to (infinitive form of puedo)", "poder"),
        ("I can", "yo puedo"),
    ],

    "Numbers": [
        ("one", "uno"),
        ("two", "dos"),
        ("three", "tres"),
        ("four", "cuatro"),
        ("five", "cinco"),
        ("six", "seis"),
        ("seven", "siete"),
        ("eight", "ocho"),
        ("nine", "nueve"),
        ("ten", "diez"),
        ("eleven", "once"),
        ("twelve", "doce"),
        ("thirteen", "trece"),
        ("fourteen", "catorce"),
        ("fifteen", "quince"),
        ("sixteen", "dieciséis"),
        ("seventeen", "diecisiete"),
        ("eighteen", "dieciocho"),
        ("nineteen", "diecinueve"),
        ("twenty", "veinte"),
        ("thirty", "treinta"),
        ("forty", "cuarenta"),
        ("fifty", "cincuenta"),
        ("sixty", "sesenta"),
        ("seventy", "setenta"),
        ("eighty", "ochenta"),
        ("ninety", "noventa"),
        ("one hundred", "cien"),
        ("twenty-one", "veintiuno"),
        ("twenty-two", "veintidós"),
        ("thirty-one", "treinta y uno"),
        ("thirty-two", "treinta y dos"),
        ("thirty-three", "treinta y tres"),
        ("thirty-four", "treinta y cuatro"),
        ("thirty-five", "treinta y cinco"),
        ("thirty-six", "treinta y seis"),
        ("thirty-seven", "treinta y siete"),
        ("thirty-eight", "treinta y ocho"),
        ("thirty-nine", "treinta y nueve"),
        ("forty-four", "cuarenta y cuatro"),
        ("forty-five", "cuarenta y cinco"),
        ("fifty-six", "cincuenta y seis"),
        ("fifty-seven", "cincuenta y siete"),
        ("sixty-eight", "sesenta y ocho"),
        ("seventy-seven", "setenta y siete"),
        ("eighty-eight", "ochenta y ocho"),
        ("ninety-three", "noventa y tres"),
    ],

    "Interrogative Words": [
        ("What", "¿Qué?"),
        ("Who (singular/plural)", "¿Quién? / ¿Quiénes?"),
        ("Where", "¿Dónde?"),
        ("When", "¿Cuándo?"),
        ("Which", "¿Cuál? / ¿Cuáles?"),
        ("Why", "¿Por qué?"),
        ("How", "¿Cómo?"),
        ("How much / How many", "¿Cuánto? / ¿Cuánta? / ¿Cuántos? / ¿Cuántas?"),
    ],

    "Preguntar (Questions)": [
        ("How are (things)?", "¿Qué tal?"),
        ("How are you?", "¿Cómo estás?"),
        ("How are you? (casual)", "¿Cómo andas?"),
        ("All good?", "¿Todo bien?"),
        ("How is everything?", "¿Qué tal todo?"),
        ("How's it going (for you)?", "¿Qué tal te va?"),
        ("What's up?", "¿Qué hay?"),
        ("What are you up to?", "¿Qué te cuentas?"),
        ("How is (he/she)?", "¿Cómo está?"),
        ("How are you? (formal)", "¿Cómo se encuentra?"),
        ("How are you? (formal, alt.)", "¿Cómo le va?"),
        ("Does 'Ordenador' mean 'computer'?", "¿'Ordenador' significa 'computer'?"),
        ("Where is the protagonist located in each of the vignettes?", "¿Dónde se encuentra el protagonista en cada una de las viñetas?"),
        ("What relationship do you think there is between Francisco and the other characters?", "¿Qué relación crees que hay entre Francisco y los demás personajes?"),
        ("Which of these ways of addressing a person seem formal and which seem informal to you?", "¿Cuáles de estas formas de dirigirse a una persona te parecen formales y cuáles te parecen informales?"),
    ],

    "Responses": [
        ("very well", "muy bien"),
        ("well", "bien"),
        ("great", "genial"),
        ("all good", "todo bien"),
        ("everything great", "todo genial"),
        ("well...", "bueno..."),
        ("getting by", "tirando"),
        ("so-so, and you?", "regular, ¿y tú?"),
        ("not very well", "no muy bien"),
        ("bad", "mal"),
        ("awful", "fatal"),
    ],

    "Saludar (Greetings)": [
        ("hello", "hola"),
        ("hi / hello (neutral)", "buenas"),
        ("good morning", "buenos días"),
        ("good afternoon", "buenas tardes"),
        ("long time no see!", "¡cuánto tiempo!"),
        ("I'm glad to see you", "me alegro de verte"),
        ("nice to see you", "qué gusto verte"),
        ("so happy to see you", "qué alegría verte"),
        ("welcome (plural)", "bienvenidos"),
    ],

    "Despedirse (Goodbyes)": [
        ("goodbye", "adiós"),
        ("see you soon", "hasta pronto"),
        ("good night", "buenas noches"),
        ("see you later", "hasta luego"),
        ("see you tomorrow", "hasta mañana"),
        ("bye", "chao"),
        ("see you", "hasta la vista"),
        ("see you Monday/Tuesday", "hasta el lunes / martes"),
        ("see you another time", "hasta otra"),
        ("see you (soon)", "nos vemos (pronto)"),
        ("hope it goes well!", "¡que vaya bien!"),
    ],

    "Dialogue": [
        ("Naomi and Pedro", "Naomi y Pedro"),
        ("My name is David. Nice to meet you.", "Me llamo David. Mucho gusto."),
        ("Pleased to meet you (fem.)", "Encantada."),
        ("Fine, a little tired.", "Bien, un poco cansada."),
        ("Sleep well / rest up.", "Que descanses."),
        ("Likewise, see you tomorrow.", "Igualmente, hasta mañana."),
        ("this girl", "esta chica"),
        ("this boy", "este chico"),
        ("My name is Lucas and I am French. I am thirty-one and I am a nurse", "me llamo Lucas y soy francés. Tengo treinta y uno y soy enfermero"),
        ("His name is Lucas and he is French. He is thirty-one years old and he is a nurse", "él se llama Lucas y es francés. Tiene treinta y uno años y es enfermero"),
        ("I am in Madrid", "estoy en Madrid"),
        ("Where are you from?", "¿De dónde eres?"),
        ("How interesting!", "¡Qué interesante!"),
        ("Yes, me too. Hey, what are you doing this afternoon?", "Sí, yo también. Oye, ¿qué haces esta tarde?"),
        ("Nothing special. And you?", "Nada especial. ¿Y tú?"),
        ("I have Spanish class.", "Tengo clase de español."),
        ("Okay, I'm off now.", "Bueno, me voy ya."),
        ("Goodbye, have a good day.", "Adiós, que tengas un buen día."),
        ("Thanks, likewise.", "Gracias, igualmente."),
    ],

    "Classroom Objects": [
        ("pen", "bolígrafo"),
        ("pencil", "lápiz"),
        ("laptop", "portátil"),
        ("chair", "silla"),
        ("projector", "proyector"),
        ("whiteboard", "pizarra blanca"),
        ("tablet", "tableta"),
        ("pencil case", "estuche"),
        ("table / desk", "mesa"),
        ("book", "libro"),
        ("notebook", "cuaderno"),
        ("sheet of paper", "hoja de papel"),
        ("backpack", "mochila"),
        ("computer (alt.)", "ordenador"),
        ("ruler", "regla"),
        ("scissors", "tijeras"),
        ("calculator", "calculadora"),
        ("eraser", "borrador"),
        ("sharpener", "sacapuntas"),
        ("camera", "cámara de fotos"),
        ("also / too", "también"),
    ],

    "Grammar (Tener & Plurals)": [
        ("I have three coins", "yo tengo tres monedas"),
        ("I have four things", "yo tengo cuatro cosas"),
        ("I have a pen", "yo tengo un bolígrafo"),
        ("I have a laptop", "yo tengo un portátil"),
        ("I have a table", "yo tengo una mesa"),
        ("I don’t have the books", "yo no tengo los libros"),
        ("I don’t have a glass of water", "yo no tengo un vaso de agua"),
        ("I don’t have the glasses", "yo no tengo las gafas"),
        ("plural of lápiz", "lápices"),
        ("plural of silla", "sillas"),
        ("plural of portátil", "portátiles"),
        ("plural of hoja de papel", "hojas de papel"),
        ("the ball", "el balón"),
        ("the balls", "los balones"),
        ("the plant", "la planta"),
        ("the plants", "las plantas"),
    ],

    "Requests & Needs": [
        ("I like to draw with a pencil", "me gusta dibujar con un lápiz"),
        ("Can you lend me a blue pen?", "¿me dejas un boli azul?"),
        ("I have a yellow highlighter", "tengo un subrayador amarillo"),
        ("This pencil has no tip", "este lápiz no tiene punta"),
        ("I need a sharpener", "¡necesito un sacapuntas!"),
        ("Can you lend me your eraser?", "¿me prestas tu borrador?"),
        ("I have to look for a house", "tengo que buscar una casa"),
        ("In maths class we use calculators", "en clase de matemáticas utilizamos calculadoras"),
        ("I keep all my things in my backpack", "guardo todas mis cosas en mi mochila"),
        ("In my notebook I write with a pen", "en mi cuaderno escribo con bolígrafo"),
        ("The teacher writes on the board", "la profesora escribe en la pizarra"),
        ("A pair of glasses", "un par de gafas"),
        ("With a ruler you can make straight lines", "con la regla puedes hacer líneas rectas"),
    ],

    "Feelings & Concepts": [
        ("sun", "sol"),
        ("star", "estrella"),
        ("dawn", "alborada"),
        ("trust / confidence", "confianza"),
        ("bat (animal)", "murciélago"),
        ("we dance", "bailamos"),
        ("thank you", "gracias"),
        ("feeling", "sentimiento"),
        ("solidarity", "la solidaridad"),
        ("mother", "madre"),
        ("joy / happiness", "alegría"),
        ("lawyer", "abogado"),
        ("football / soccer", "fútbol"),
        ("I desire love", "deseo amor"),
        ("to love / to want", "querer"),
        ("male / macho", "macho"),
        ("researcher / investigator", "investigador"),
        ("beauty", "belleza"),
        ("you (informal)", "tú"),
        ("affection / darling", "cariño"),
        ("mellifluous / sweet-sounding", "melíflua"),
        ("I am sleepy", "yo tengo sueño"),
        ("I have a dream", "yo tengo un sueño"),
        ("beside oneself / out of one's mind", "fuera de sí"),
        ("cold (weather/feeling)", "frío"),
        ("heat/hot weather", "calor"),
        ("hot (object/drink - different from calor)", "caliente"),
        ("I feel cold", "siento frío"),
        ("I am cold (have coldness)", "tengo frío"),
        ("I feel hot", "siento calor"),
        ("I am hot (have heat)", "tengo calor"),
        ("The coffee is hot", "El café está caliente"),
        ("I am energetic", "soy energía"),
        ("I am a bit tired", "soy un poco cansado"),
        ("town/village", "pueblo"),
        ("villa", "villa"),
        ("small village", "aldea"),
        ("exchange", "intercambio"),
        ("We all have a table in class", "tengamos una mesa en clase"),
        ("We all have a computer at home", "tengamos una computadora en casa"),
        ("from", "desde"),
        ("I read many books", "yo leo muchos libros"),
        ("conjugation", "conjugación"),
        ("I always want more money", "siempre quiero más dinero"),
        ("guanabana (Colombian drink)", "guanábana"),
        ("lulo (Colombian drink)", "lulo"),
        ("tostones (Colombian food)", "tostones"),
        ("plantains", "plátanos"),
        ("how much is", "cuánto es"),
        ("very delicious", "muy delicioso"),
        ("your next vacation", "tus próximas vacaciones"),
        ("I go to Ecuador", "yo voy Ecuador"),
        ("my next vacation I'm going to Ireland", "mis próximas vacaciones yo voy ir Irlanda"),
        ("I like to go to the forest", "me gusta ir al bosque"),
        ("I like to go to other countries", "me gusta ir a otros países"),
        ("after/afterwards", "después"),
        ("because (both why and because)", "porque"),
        ("country", "país"),
    ],

    "Virtues & Abstract Words": [
        ("truth", "verdad"),
        ("loyalty", "lealtad"),
        ("confidence", "confianza"),
        ("spirit", "espíritu"),
        ("love", "amor"),
    ],

    "Miscellaneous": [
        ("How was it? It was...", "¿Cómo fue? Fue..."),
        ("It was easy / difficult / so-so / more or less", "fue fácil / difícil / así así / más o menos"),
        ("the mountain peak", "la punta de la montaña"),
        ("I need food", "necesito comida"),
        ("I need a cup of wine", "necesito una copa de vino"),
        ("Do you have anything?", "¿tienes algo?"),
        ("You have nothing", "no tienes nada"),
        ("other languages", "otras lenguas"),
        ("come se escribe __ en español", "¿cómo se escribe __ en español?"),
        ("how do you pronounce 'pizarra'?", "¿cómo se pronuncia 'pizarra'?"),
        ("the others / the rest", "los demás"),
        ("you believe / think", "crees"),
        ("between", "entre"),
        ("to address / to direct oneself to", "dirigirse"),
        ("formal (plural)", "formales"),
        ("ways / forms", "formas"),
        ("they seem formal", "parecen formales"),
        ("languages", "lenguas"),
        ("work / job", "trabajo"),
        ("nationality", "nacionalidad"),
        ("email", "correo"),
        ("Jiménez (surname)", "Jiménez"),
        ("Zumba", "Zumba"),
        ("a novel", "una novela"),
        ("an exchange", "un intercambio"),
        ("the radio", "la radio"),
        ("a book", "un libro"),
        ("a diary", "un diario"),
        ("with natives", "con nativos"),
        ("music", "música"),
        ("series", "series"),
        ("a movie", "una película"),
        ("pronunciation", "la pronunciación"),
        ("a Spanish course", "un curso de español"),
        ("exercises", "ejercicios"),
        ("television", "la televisión"),
        ("on foot", "a pie"),
        ("horse", "caballo"),
        ("boat", "barco"),
        ("bus", "autobús"),
        ("car", "coche"),
        ("bicycle", "bicicleta"),
        ("cinema", "cine"),
        ("countryside", "campo"),
        ("beach", "playa"),
        ("mountain", "montaña"),
        ("store", "tienda"),
        ("shopping", "compras"),
        ("drinks", "copas"),
        ("vacation", "vacaciones"),
        ("masculine", "masculino"),
        ("feminine", "femenino"),
        ("we say", "decimos"),
        ("place", "lugar"),
        ("before / in front of", "ante"),
        ("to see", "ver"),
        ("mother", "madre"),
        ("networks", "redes"),
        ("gaspacho", "gaspacho"),
        ("Do you have any ideas for this weekend?", "¿Tienes algunas ideas para este fin de semana?"),
        ("What things from the list do you want to do?", "¿Qué cosas de la lista quiere hacer?"),
        ("I want to go on an excursion", "Quiero ir de excursión"),
        ("Do you want to do any of those things on the weekend?", "¿Quieres hacer alguna de esas cosas el fin de semana?"),
        ("Do you want to do others?", "¿Quieres hacer otras?"),
        ("On Saturday, I want to go out at night. And you?", "Yo, el sábado, quiero salir de noche. ¿Y tú?"),
        ("Me too. And I want to go to the cinema.", "Yo también. Y quiero ir al cine."),
        ("Well, I want to go on an excursion to...", "Pues yo quiero ir de excursión a..."),
        ("Me too", "Yo también"),
        ("I do", "Yo sí"),
        ("I don't", "Yo no"),
        ("Me neither", "Yo tampoco"),
        ("To communicate", "Para comunicar"),
        ("I want to have Spanish-speaking friends", "Yo quiero tener amigos de habla hispana"),
        ("My colleague John wants to live in Peru", "Mi compañero John quiere vivir en Perú"),
        ("Anne and I want to study at a Latin American university and spend vacation in Cuba", "Anne y yo queremos estudiar en una universidad latinoamericana y pasar las vacaciones en Cuba"),
        ("Katerina and Michael want to spend vacation in Spain and learn other languages", "Katerina y Michael quieren pasar las vacaciones en España y aprender otros idiomas"),
    ],

    "Common Verbs & Phrases": [
        ("to leave / to let", "dejar"),
        ("I leave / I let", "dejo"),
        ("I leave you a pencil", "te dejo un lápiz"),
        ("to take / to drink", "tomar"),
        ("take (here you go)", "toma"),
        ("to work", "trabajar"),
        ("to sing", "cantar"),
        ("to eat", "comer"),
        ("to live", "vivir"),
        ("languages", "idiomas"),
        ("él trabaja __ camarero", "de"),
        ("trabaja __ __ restaurante", "en un"),
        ("all verbs end in?", "ar, er, ir"),
        ("idiomas", "languages"),
        ("however", "sin embargo"),
        ("additionally", "además"),
        ("extroverted", "extrovertidos"),
        ("calm / peaceful", "tranquilo"),
        ("so / so much", "tan"),
        ("relaxed", "relajado"),
        ("will be / will go (future third person)", "será"),
        ("recipes", "recetas"),
        ("to start / to begin", "empezar"),
        ("better", "mejor"),
        ("What do you do to practice Spanish?", "¿Qué haces para practicar español?"),
        ("together", "juntos"),
        ("early", "temprano"),
    ],

    "Math & Quantities": [
        ("more", "más"),
        ("less / minus", "menos"),
        ("nine plus one equals ten", "nueve más uno = diez"),
        ("two hundred", "dos cientos"),
        ("eight hundred", "ocho cientos"),
    ],

    "Prepositions & Contractions": [
        ("to", "a"),
        ("to the (contraction)", "al (a + el)"),
        ("to the (feminine)", "a la"),
        ("of/from", "de"),
        ("to go on foot", "ir a pie"),
        ("to go by horse", "ir a caballo"),
        ("to go by/in", "ir en"),
        ("in/on", "en"),
        ("with", "con"),
        ("without", "sin"),
        ("for/by", "por"),
        ("for/to", "para"),
        ("under", "debajo de"),
        ("over/above", "encima de"),
        ("behind", "detrás de"),
        ("in front of", "delante de"),
        ("next to", "al lado de"),
        ("between", "entre"),
        ("inside", "dentro de"),
        ("outside", "fuera de"),
        ("near", "cerca de"),
        ("far from", "lejos de"),
        ("through", "a través de"),
        ("during", "durante"),
        ("since", "desde"),
        ("until", "hasta"),
        ("before", "antes de"),
        ("after", "después de"),
        ("around", "alrededor de"),
        ("according to", "según"),
        ("I am at home", "estoy en casa"),
        ("She goes to work", "ella va al trabajo"),
        ("The book is on the table", "el libro está en la mesa"),
        ("We walk with friends", "caminamos con amigos"),
        ("I study without music", "estudio sin música"),
        ("He works for his family", "trabaja por su familia"),
        ("This is for you", "esto es para ti"),
        ("The cat is under the chair", "el gato está debajo de la silla"),
        ("The picture is above the sofa", "el cuadro está encima del sofá"),
        ("The bank is behind the church", "el banco está detrás de la iglesia"),
        ("I sit in front of the computer", "me siento delante del ordenador"),
        ("The school is next to the park", "la escuela está al lado del parque"),
        ("Choose between coffee and tea", "elige entre café y té"),
        ("The keys are inside the bag", "las llaves están dentro del bolso"),
        ("We wait outside the store", "esperamos fuera de la tienda"),
        ("I live near the beach", "vivo cerca de la playa"),
        ("The hospital is far from here", "el hospital está lejos de aquí"),
        ("To practice prepositions", "Practicar las preposiciones"),
    ],

    "Nationalities & Countries": [
        ("Canadian", "canadiense"),
        ("Canada", "Canadá"),
        ("Brazilian (masc.)", "brasileño"),
        ("Brazilian (fem.)", "brasileña"),
        ("Brazil", "Brasil"),
        ("German (masc.)", "alemán"),
        ("German (fem.)", "alemana"),
        ("Germany", "Alemania"),
        ("Moroccan (masc.)", "marroquí"),
        ("Moroccan (fem.)", "marroquí"),
        ("Morocco", "Marruecos"),
        ("Argentine (masc.)", "argentino"),
        ("Argentine (fem.)", "argentina"),
        ("Argentina", "Argentina"),
        ("French (masc.)", "francés"),
        ("French (fem.)", "francesa"),
        ("France", "Francia"),
        ("English (masc.)", "inglés"),
        ("English (fem.)", "inglesa"),
        ("He is French", "es francés"),
        ("She is French", "es francesa"),
        ("He is Italian", "es italiano"),
        ("She is Italian", "es italiana"),
        ("American / from the U.S.", "estadounidense"),
        ("Scottish (fem.)", "escocesa"),
        ("Belgian", "belga"),
        ("England", "Inglaterra"),
        ("Spain", "España"),
        ("Switzerland", "Suiza"),
        ("Chile", "Chile"),
        ("Norway", "Noruega"),
        ("Sweden", "Suecia"),
        ("Algeria", "Argelia"),
        ("Russian (fem.)", "rusa"),
        ("Russian (masc.)", "ruso"),
        ("Denmark", "Dinamarca"),
        ("Panamanian", "panameño"),
        ("Venezuelan", "venezolano"),
        ("Cuban", "cubano"),
        ("Chilean", "chileno"),
        ("Peruvian", "peruano"),
        ("Ecuadorian", "ecuatoriano"),
        ("Maltese (masc.)", "maltés"),
        ("Maltese (fem.)", "maltesa"),
        ("Poland", "Polonia"),
        ("Polish (masc.)", "polaco"),
        ("Lithuanian (masc.)", "lituano"),
        ("Lithuanian (fem.)", "lituana"),
        ("Indonesian (fem.)", "indonesia"),
        ("Indonesian (masc.)", "indonesio"),
        ("Irish", "irlandés"),
        ("In pairs, think of four things and write the nationality you associate with each one",
         "En parejas, pensad cuatro cosas y escribid la nacionalidad con la que relacionáis cada una."),
        ("Greek (masc.)", "griego"),
        ("Greek (fem.)", "griega"),
        ("Dutch (masc.)", "holandés"),
        ("Dutch (fem.)", "holandesa"),
        ("Belgium", "Bélgica"),
        ("Ukrainian (fem.)", "ucraniana"),
        ("Ukraine", "Ucrania"),
        ("I am Ukrainian", "soy ucraniana"),
        ("I am from Ukraine", "soy de Ucrania"),
        ("My name is Antonio, I am from Peru", "me llamo Antonio, soy de Perú"),
        ("My name is Jacob, I am Belgian", "me llamo Jacob, soy belga"),
        ("My name is John, I am British, I am from the United Kingdom", "me llamo John, soy británico, soy del Reino Unido"),
        ("Canadian is from Canada, right?", "Canadiense es de Canadá, ¿no?"),
        ("Yes. How do you write Canada in Spanish?", "Sí. ¿Cómo se escribe Canadá en español?"),
        ("Brazilian is from Brazil, right?", "Brasileño es de Brasil, ¿no?"),
        ("Yes. How do you write Brazil in Spanish?", "Sí. ¿Cómo se escribe Brasil en español?"),
        ("German is from Germany, right?", "Alemán es de Alemania, ¿no?"),
        ("Yes. How do you write Germany in Spanish?", "Sí. ¿Cómo se escribe Alemania en español?"),
        ("Moroccan is from Morocco, right?", "Marroquí es de Marruecos, ¿no?"),
        ("Yes. How do you write Morocco in Spanish?", "Sí. ¿Cómo se escribe Marruecos en español?"),
        ("Argentine is from Argentina, right?", "Argentino es de Argentina, ¿no?"),
        ("Yes. How do you write Argentina in Spanish?", "Sí. ¿Cómo se escribe Argentina en español?"),
        ("French (fem.) is from France, right?", "Francesa es de Francia, ¿no?"),
        ("Yes. How do you write France in Spanish?", "Sí. ¿Cómo se escribe Francia en español?"),
        ("Guinean", "guineano"),
        ("Nicaraguan", "nicaragüense"),
        ("Swiss", "suizo"),
        ("Portuguese (masc.)", "portugués"),
        ("Portuguese (fem.)", "portuguesa"),
        ("Spanish (masc.)", "español"),
        ("Spanish (fem.)", "española"),
        ("Brazilian (fem.)", "brasileña"),
        ("Chilean (fem.)", "chilena"),
        ("American (masc.)", "americano"),
        ("American (fem.)", "americana"),
        ("Italian (masc.)", "italiano"),
        ("Italian (fem.)", "italiana"),
        ("Japanese (masc.)", "japonés"),
        ("Japanese (fem.)", "japonesa"),
        ("Chinese (masc.)", "chino"),
        ("Chinese (fem.)", "china"),
        ("Indian (masc.)", "indio"),
        ("Indian (fem.)", "india"),
        ("Mexican (masc.)", "mexicano"),
        ("Mexican (fem.)", "mexicana"),
        ("Dutch (masc.)", "holandés"),
        ("Dutch (fem.)", "holandesa"),
        ("Portuguese (masc.)", "portugués"),
        ("Portuguese (fem.)", "portuguesa"),
        ("Turkish (masc.)", "turco"),
        ("Turkish (fem.)", "turca"),
        ("Greek (masc.)", "griego"),
        ("Greek (fem.)", "griega"),
        ("Austrian (masc.)", "austriaco"),
        ("Austrian (fem.)", "austriaca"),
        ("Czech (masc.)", "checo"),
        ("Czech (fem.)", "checa"),
        ("Slovak (masc.)", "eslovaco"),
        ("Slovak (fem.)", "eslovaca"),
        ("Hungarian (masc.)", "húngaro"),
        ("Hungarian (fem.)", "húngara"),
        ("Romanian (masc.)", "rumano"),
        ("Romanian (fem.)", "rumana"),
        ("Bulgarian (masc.)", "búlgaro"),
        ("Bulgarian (fem.)", "búlgara"),
        ("Serbian (masc.)", "serbio"),
        ("Serbian (fem.)", "serbia"),
        ("Croatian (masc.)", "croata"),
        ("Croatian (fem.)", "croata"),
        ("Slovenian (masc.)", "esloveno"),
        ("Slovenian (fem.)", "eslovena"),
        ("Albanian (masc.)", "albanés"),
        ("Albanian (fem.)", "albanesa"),
        ("Icelandic (masc.)", "islandés"),
        ("Icelandic (fem.)", "islandesa"),
        ("Finnish (masc.)", "finlandés"),
        ("Finnish (fem.)", "finlandesa"),
        ("Estonian (masc.)", "estonio"),
        ("Estonian (fem.)", "estonia"),
        ("Latvian (masc.)", "letón"),
        ("Latvian (fem.)", "letona"),
        ("Australian (masc.)", "australiano"),
        ("Australian (fem.)", "australiana"),
        ("New Zealander (masc.)", "neozelandés"),
        ("New Zealander (fem.)", "neozelandesa"),
        ("South African (masc.)", "sudafricano"),
        ("South African (fem.)", "sudafricana"),
        ("Egyptian (masc.)", "egipcio"),
        ("Egyptian (fem.)", "egipcia"),
        ("Tunisian (masc.)", "tunecino"),
        ("Tunisian (fem.)", "tunecina"),
        ("Libyan (masc.)", "libio"),
        ("Libyan (fem.)", "libia"),
        ("Sudanese (masc.)", "sudanés"),
        ("Sudanese (fem.)", "sudanesa"),
        ("Ethiopian (masc.)", "etíope"),
        ("Ethiopian (fem.)", "etíope"),
        ("Kenyan (masc.)", "keniano"),
        ("Kenyan (fem.)", "keniana"),
        ("Tanzanian (masc.)", "tanzano"),
        ("Tanzanian (fem.)", "tanzana"),
        ("Ugandan (masc.)", "ugandés"),
        ("Ugandan (fem.)", "ugandesa"),
        ("Rwandan (masc.)", "ruandés"),
        ("Rwandan (fem.)", "ruandesa"),
        ("Ghanaian (masc.)", "ghanés"),
        ("Ghanaian (fem.)", "ghanesa"),
        ("Nigerian (masc.)", "nigeriano"),
        ("Nigerian (fem.)", "nigeriana"),
        ("Israeli (masc.)", "israelí"),
        ("Israeli (fem.)", "israelí"),
        ("Palestinian (masc.)", "palestino"),
        ("Palestinian (fem.)", "palestina"),
        ("Lebanese (masc.)", "libanés"),
        ("Lebanese (fem.)", "libanesa"),
        ("Syrian (masc.)", "sirio"),
        ("Syrian (fem.)", "siria"),
        ("Jordanian (masc.)", "jordano"),
        ("Jordanian (fem.)", "jordana"),
        ("Iraqi (masc.)", "iraquí"),
        ("Iraqi (fem.)", "iraquí"),
        ("Iranian (masc.)", "iraní"),
        ("Iranian (fem.)", "iraní"),
        ("Saudi (masc.)", "saudí"),
        ("Saudi (fem.)", "saudí"),
        ("Afghan (masc.)", "afgano"),
        ("Afghan (fem.)", "afgana"),
        ("Pakistani (masc.)", "paquistaní"),
        ("Pakistani (fem.)", "paquistaní"),
        ("Bangladeshi (masc.)", "bangladesí"),
        ("Bangladeshi (fem.)", "bangladesí"),
        ("Thai (masc.)", "tailandés"),
        ("Thai (fem.)", "tailandesa"),
        ("Vietnamese (masc.)", "vietnamita"),
        ("Vietnamese (fem.)", "vietnamita"),
        ("Malaysian (masc.)", "malasio"),
        ("Malaysian (fem.)", "malasia"),
        ("Singaporean (masc.)", "singapurense"),
        ("Singaporean (fem.)", "singapurense"),
        ("Filipino (masc.)", "filipino"),
        ("Filipino (fem.)", "filipina"),
        ("Korean (masc.)", "coreano"),
        ("Korean (fem.)", "coreana"),
        ("Mongolian (masc.)", "mongol"),
        ("Mongolian (fem.)", "mongola"),
        ("Kazakh (masc.)", "kazajo"),
        ("Kazakh (fem.)", "kazaja"),
        ("Uzbek (masc.)", "uzbeko"),
        ("Uzbek (fem.)", "uzbeka"),
        ("Georgian (masc.)", "georgiano"),
        ("Georgian (fem.)", "georgiana"),
        ("Armenian (masc.)", "armenio"),
        ("Armenian (fem.)", "armenia"),
        ("Azerbaijani (masc.)", "azerbaiyano"),
        ("Azerbaijani (fem.)", "azerbaiyana"),
        ("Belarusian (masc.)", "bielorruso"),
        ("Belarusian (fem.)", "bielorrusa"),
        ("Moldovan (masc.)", "moldavo"),
        ("Moldovan (fem.)", "moldava"),
    ],

    "Workplaces": [
        ("a university", "una universidad"),
        ("a gym", "un gimnasio"),
        ("a laboratory", "un laboratorio"),
        ("a hospital", "un hospital"),
        ("a newspaper", "un periódico"),
        ("a bar", "un bar"),
        ("a restaurant", "un restaurante"),
        ("a workshop", "un taller"),
        ("a bank", "un banco"),
        ("places of work", "lugares de trabajo"),
        ("a transport company", "una empresa de transportes"),
        ("a telecommunications company", "una empresa de telecomunicaciones"),
        ("a law firm", "un despacho de abogados"),
        ("an architecture firm", "un despacho de arquitectos"),
        ("an advertising agency", "una agencia de publicidad"),
        ("a travel agency", "una agencia de viajes"),
        ("a store", "una tienda"),
        ("a supermarket", "un supermercado"),
        ("a language school", "una escuela de lenguas"),
        ("a yoga school", "una escuela de yoga"),
    ],

    "Professions": [
        ("pronunciation", "pronunciación"),
        ("painter (masc.)", "pintor"),
        ("painter (fem.)", "pintora"),
        ("writer (masc.)", "escritor"),
        ("writer (fem.)", "escritora"),
        ("teacher (masc.)", "profesor"),
        ("teacher (fem.)", "profesora"),
        ("student", "estudiante"),
        ("journalist", "periodista"),
        ("salesperson / commercial agent", "comercial"),
        ("driver / chauffeur", "chófer"),
        ("agent", "agente"),
        ("police officer", "policía"),
        ("model", "modelo"),
        ("fashion designer", "diseñador/a de moda"),
        ("librarian (masc.)", "bibliotecario"),
        ("librarian (fem.)", "bibliotecaria"),
        ("employee (masc.)", "empleado"),
        ("employee (fem.)", "empleada"),
        ("waiter", "camarero"),
        ("waitress", "camarera"),
        ("hairdresser (masc.)", "peluquero"),
        ("hairdresser (fem.)", "peluquera"),
        ("doctor (masc.)", "doctor"),
        ("doctor (fem.)", "doctora"),
        ("translator", "traductor"),
        ("nurse (masc.)", "enfermero"),
        ("engineer (masc.)", "ingeniero"),
        ("engineer (fem.)", "ingeniera"),
        ("lawyer (masc.)", "abogado"),
        ("lawyer (fem.)", "abogada"),
        ("architect (fem.)", "arquitecta"),
        ("architect (masc.)", "arquitecto"),
        ("editor (masc.)", "editor"),
        ("editor (fem.)", "editora"),
        ("bookstore", "librería"),
        ("shop assistant", "dependiente"),
        ("vendor / seller", "vendedor"),
        ("occupational therapist", "terapeuta ocupacional"),
        ("systems engineer", "ingeniero de sistemas"),
        ("dentist", "dentista"),
        ("homemaker", "ama de casa"),
        ("midwife", "matrona"),
        ("father", "padre"),
        ("carpenter", "tablador"),
        ("artist", "artista"),
        ("counsellor", "consejero"),
        ("accountant", "contador"),
        ("quantitative analyst (masc.)", "analista cuantitativo"),
        ("quantitative analyst (fem.)", "analista cuantitativa"),
        ("hospital", "hospital"),
        ("shop / store", "tienda"),
        ("laboratory", "laboratorio"),
        ("receptionist", "recepcionista"),
        ("language school", "escuela de idiomas"),
        ("gynecologist", "ginecólogo"),
        ("judge (fem.)", "jueza"),
        ("blogger", "bloguero"),
        ("surgeon (fem.)", "cirujana"),
        ("boss / chief (fem.)", "jefa"),
        ("engineer (fem.)", "ingeniera"),
        ("linguist", "lingüista"),
        ("psychologist", "psicólogo"),
        ("doctor (fem.)", "médica"),
        ("architect", "arquitecto"),
        ("She works as a waitress and works in a hospital", "trabaja de camarera y trabaja en un hospital"),
        ("He works as a shop assistant and works in a store", "trabaja de dependiente y trabaja en una tienda"),
        ("She works as a scientist and works in a laboratory", "trabaja de científica y trabaja en un laboratorio"),
        ("He works as a receptionist and works in a language school", "trabaja de recepcionista y trabaja en una escuela de idiomas"),
        ("judge (masc.)", "juez"),
        ("judge (fem.)", "jueza"),
        ("thief (masc.)", "ladrón"),
        ("thief (fem.)", "ladrona"),
        ("My friend Carl is a nurse and works at his patients' house", "mi amigo Carl es enfermero y trabaja en una casa de sus pacientes"),
        ("My friend Alex is a software engineer and works in an office", "mi amigo Alex es ingeniero de software y trabaja en una oficina"),
        ("My friend Ross is in business and works from home", "mi amigo Ross está en el negocio y trabaja desde casa"),
        ("scientist (masc.)", "científico"),
        ("scientist (fem.)", "científica"),
        ("cook / chef (masc.)", "cocinero"),
        ("cook / chef (fem.)", "cocinera"),
        ("designer (masc.)", "diseñador"),
        ("designer (fem.)", "diseñadora"),
        ("journalist (masc.)", "periodista"),
        ("journalist (fem.)", "periodista"),
        ("professor (masc.)", "profesor"),
        ("professor (fem.)", "profesora"),
        ("translator (masc.)", "traductor"),
        ("translator (fem.)", "traductora"),
        ("nurse (masc.)", "enfermero"),
        ("nurse (fem.)", "enfermera"),
        ("secretary (masc.)", "secretario"),
        ("secretary (fem.)", "secretaria"),
        ("athlete (masc.)", "deportista"),
        ("athlete (fem.)", "deportista"),
        ("commercial agent (masc.)", "comercial"),
        ("commercial agent (fem.)", "comercial"),
        ("urban artist (fem.)", "artista urbana"),
        ("professional footballer (fem.)", "futbolista profesional"),
        ("actress", "actriz"),
    ],

    "Countries": [
        ("United States", "Estados Unidos"),
        ("United Kingdom", "Reino Unido"),
        ("Italy", "Italia"),
        ("Japan", "Japón"),
        ("China", "China"),
        ("India", "India"),
        ("Mexico", "México"),
        ("Netherlands", "Países Bajos"),
        ("Portugal", "Portugal"),
        ("Russia", "Rusia"),
        ("Turkey", "Turquía"),
        ("Greece", "Grecia"),
        ("Austria", "Austria"),
        ("Czech Republic", "República Checa"),
        ("Slovakia", "Eslovaquia"),
        ("Hungary", "Hungría"),
        ("Romania", "Rumania"),
        ("Bulgaria", "Bulgaria"),
        ("Serbia", "Serbia"),
        ("Croatia", "Croacia"),
        ("Slovenia", "Eslovenia"),
        ("Bosnia and Herzegovina", "Bosnia y Herzegovina"),
        ("Montenegro", "Montenegro"),
        ("Macedonia", "Macedonia"),
        ("Albania", "Albania"),
        ("Malta", "Malta"),
        ("Cyprus", "Chipre"),
        ("Iceland", "Islandia"),
        ("Finland", "Finlandia"),
        ("Estonia", "Estonia"),
        ("Latvia", "Letonia"),
        ("Lithuania", "Lituania"),
        ("Ireland", "Irlanda"),
        ("Scotland", "Escocia"),
        ("Wales", "Gales"),
        ("Australia", "Australia"),
        ("New Zealand", "Nueva Zelanda"),
        ("South Africa", "Sudáfrica"),
        ("Egypt", "Egipto"),
        ("Tunisia", "Túnez"),
        ("Libya", "Libia"),
        ("Sudan", "Sudán"),
        ("Ethiopia", "Etiopía"),
        ("Kenya", "Kenia"),
        ("Tanzania", "Tanzania"),
        ("Uganda", "Uganda"),
        ("Rwanda", "Ruanda"),
        ("Ghana", "Ghana"),
        ("Nigeria", "Nigeria"),
        ("Senegal", "Senegal"),
        ("Mali", "Malí"),
        ("Burkina Faso", "Burkina Faso"),
        ("Ivory Coast", "Costa de Marfil"),
        ("Guinea", "Guinea"),
        ("Sierra Leone", "Sierra Leona"),
        ("Liberia", "Liberia"),
        ("Togo", "Togo"),
        ("Benin", "Benin"),
        ("Niger", "Níger"),
        ("Chad", "Chad"),
        ("Central African Republic", "República Centroafricana"),
        ("Cameroon", "Camerún"),
        ("Equatorial Guinea", "Guinea Ecuatorial"),
        ("Gabon", "Gabón"),
        ("Democratic Republic of the Congo", "República Democrática del Congo"),
        ("Republic of the Congo", "República del Congo"),
        ("Angola", "Angola"),
        ("Zambia", "Zambia"),
        ("Zimbabwe", "Zimbabue"),
        ("Botswana", "Botsuana"),
        ("Namibia", "Namibia"),
        ("Lesotho", "Lesoto"),
        ("Swaziland", "Suazilandia"),
        ("Madagascar", "Madagascar"),
        ("Mauritius", "Mauricio"),
        ("Seychelles", "Seychelles"),
        ("Comoros", "Comoras"),
        ("Djibouti", "Yibuti"),
        ("Somalia", "Somalia"),
        ("Eritrea", "Eritrea"),
        ("Israel", "Israel"),
        ("Palestine", "Palestina"),
        ("Lebanon", "Líbano"),
        ("Syria", "Siria"),
        ("Jordan", "Jordania"),
        ("Iraq", "Irak"),
        ("Iran", "Irán"),
        ("Kuwait", "Kuwait"),
        ("Saudi Arabia", "Arabia Saudí"),
        ("United Arab Emirates", "Emiratos Árabes Unidos"),
        ("Qatar", "Catar"),
        ("Bahrain", "Baréin"),
        ("Oman", "Omán"),
        ("Yemen", "Yemen"),
        ("Afghanistan", "Afganistán"),
        ("Pakistan", "Pakistán"),
        ("Bangladesh", "Bangladés"),
        ("Sri Lanka", "Sri Lanka"),
        ("Maldives", "Maldivas"),
        ("Nepal", "Nepal"),
        ("Bhutan", "Bután"),
        ("Myanmar", "Birmania"),
        ("Thailand", "Tailandia"),
        ("Laos", "Laos"),
        ("Cambodia", "Camboya"),
        ("Vietnam", "Vietnam"),
        ("Malaysia", "Malasia"),
        ("Singapore", "Singapur"),
        ("Indonesia", "Indonesia"),
        ("Brunei", "Brunéi"),
        ("Philippines", "Filipinas"),
        ("South Korea", "Corea del Sur"),
        ("North Korea", "Corea del Norte"),
        ("Mongolia", "Mongolia"),
        ("Kazakhstan", "Kazajistán"),
        ("Uzbekistan", "Uzbekistán"),
        ("Turkmenistan", "Turkmenistán"),
        ("Tajikistan", "Tayikistán"),
        ("Kyrgyzstan", "Kirguistán"),
        ("Belarus", "Bielorrusia"),
        ("Moldova", "Moldavia"),
        ("Georgia", "Georgia"),
        ("Armenia", "Armenia"),
        ("Azerbaijan", "Azerbaiyán"),
    ],

    "Transportation & Going Places": [
        ("to go shopping", "ir de compras"),
        ("to go by plane", "ir en avión"),
        ("to go on foot", "ir a pie"),
        ("to Spain", "a España"),
        ("to Latin America", "a latinoamérica"),
        ("to the cinema (to a place)", "al cine"),
        ("to the countryside (to a place)", "al campo"),
        ("to the beach (to a place)", "a la playa"),
        ("I go shopping on the weekend", "yo voy de compras el fin de semana"),
        ("I go to swim", "yo voy a nadar"),
        ("I go home by car", "yo voy a casa en carro"),
        ("I go home by train", "yo voy a casa en tren"),
        ("I go home by bus", "yo voy a casa en autobús"),
        ("I go to a Japanese restaurant on foot", "yo voy a pie un restaurante de japonés")
    ],

    "Food & Culture": [
        ("The tango is Argentine", "el tango es argentino"),
        ("Sushi is Japanese", "el sushi es japonés"),
        ("Pizza is Italian", "la pizza es italiana"),
        ("Flamenco is Spanish", "el flamenco es español"),
        ("The balalaika is Russian", "la balalaika es rusa"),
        ("The croissant is French", "el cruasán es francés"),
        ("The baguette is French", "la baguette es francesa"),
        ("Big Ben is British", "el Big Ben es británico"),
        ("Big Ben is English", "el Big Ben es inglés"),
        ("Paella is Spanish", "la paella es española"),
        ("The city is Chinese", "la ciudad es china"),
        ("Curry is Indian", "el curry es indio"),
        ("The hamburger is American", "la hamburguesa es estadounidense"),
        ("From which country do these things come?", "¿De qué país proceden estas cosas?"),
        ("Write in your notebook the nationality that corresponds to them",
         "Escribe en tu cuaderno la nacionalidad que les corresponde"),
        ("Be careful with gender!", "¡Cuidado con el género!"),
        ("arepas", "arepas"),
        ("tostones", "tostones"),
    ],

    "Grammar (Articles & Gender)": [
        ("to the (abbreviation)", "al (a + el)"),
        ("from the (abbreviation)", "del (de + el)"),
        ("some (masculine)", "unos"),
        ("some (feminine)", "unas"),
        ("determined / definite", "determinados"),
        ("undetermined / indefinite", "indeterminados"),
        ("some pens", "unos bolígrafos"),
        ("some tables", "unas mesas"),
    ],

    "Pronunciation Practice": [
        ("pronunciation pattern: gi", "gi"),
        ("pronunciation pattern: ge", "ge"),
        ("pronunciation pattern: ga", "ga"),
        ("pronunciation pattern: go", "go"),
        ("pronunciation pattern: gu", "gu"),
        ("pronunciation pattern: gue", "gue"),
        ("pronunciation pattern: gui", "gui"),
        ("cook / chef", "cocinero"),
    ],

    "Mini Dialogues": [
        ("What", "qué"),
        ("Where", "dónde"),
        ("What do you do for a living?", "¿A qué te dedicas?"),
        ("What do you do for a living? (formal)", "¿A qué se dedica usted?"),
        ("¿a qué te dedicas?", "What do you do for a living?"),
        ("¿a qué se dedica?", "What do you do for a living? (formal)"),
        ("What is your name?", "¿cómo te llamas?"),
        ("What is your name? (formal)", "¿cuál es su nombre?"),
        ("What is your name? (formal)", "¿cuál es tu nombre?"),
        ("How old are you?", "¿cuántos años tienes?"),
        ("How old are you? (formal)", "¿cuántos años tiene?"),
        ("I am 23 years old", "tengo 23 años"),
        ("You are 33 years old", "tienes 33 años"),
        ("The age 28", "la edad 28"),
        ("What is your email?", "¿cuál es tu correo electrónico?"),
        ("Do you have email?", "¿tienes correo electrónico?"),
        ("Do you have email? (formal)", "¿tiene correo electrónico?"),
        ("the email virgibtl@gmail.com", "el correo electrónico virgibtl@gmail.com"),
        ("What do you work in?", "¿en qué trabajas?"),
        ("What do you work in? (formal)", "¿en qué trabaja?"),
        ("¿en qué trabajas?", "What do you work in?"),
        ("¿en qué trabajo?", "What do I work in?"),
        ("Do you have a mobile phone?", "¿tienes móvil?"),
        ("Yes, it's 627629047", "sí, es el 627629047"),
        ("What is your phone number?", "¿cuál es tu número de teléfono?"),
        ("the mobile 63145871", "el móvil 63145871"),
        ("the cell phone 63145871", "el celular 63145871"),
        ("the phone number 914445238", "el número de teléfono 914445238"),
        ("I know", "conozco"),
        ("Then / so / in that case", "entonces"),
        ("Are you the new colleague?", "¿Tú eres el nuevo compañero?"),
        ("Do you work here at the centre or from home?", "¿Trabajas aquí en el centro o desde casa?"),
        ("Hello, my name is Andrés. I'm Argentine and a Spanish teacher. I'm 35 years old.",
         "Hola, mi nombre es Andrés. Soy argentino y soy profesor de español. Tengo 35 años."),
        ("Hello, my name is John. I work as a systems engineer and I'm English. I'm 33 years old.",
         "Hola, mi nombre es John. Trabajo de ingeniero de sistemas y soy inglés. Tengo 33 años."),
        ("I am a student and I work as a receptionist at a hotel", "soy estudiante y trabajo como recepcionista en un hotel"),
        ("I am a commercial agent", "soy comercial"),
        ("Maha works in a workshop.", "Maha en un taller."),
        ("Chloe works at a TV channel.", "Chloe en un canal de televisión."),
        ("Ulrich works in a language school.", "Ulrich en una escuela de lenguas."),
        ("Gibson works in a laboratory.", "Gibson en un laboratorio."),
        ("Andrés works at a university.", "Andrés en una universidad."),
        ("name", "nombre"),
        ("nationality", "nacionalidad"),
        ("profession", "profesión"),
        ("age", "edad"),
        ("name", "nombre"),
        ("surname / last name", "apellido"),
        ("the surname Butel", "el apellido Butel"),
        ("the surnames Rodriguez Martinez", "los apellidos Rodriguez Martinez"),
        ("What is your last name?", "¿cuál es su apellido?"),
        ("@ symbol", "arroba"),
    ],
    "Alphabet & Pronunciation": [
        ("A", "a — pronounced 'ah'"),
        ("B", "be — pronounced 'beh'"),
        ("C", "ce — before e or i, sounds like 'th' in Spain or 's' in Latin America"),
        ("Ch", "che — pronounced 'cheh'"),
        ("D", "de — pronounced 'deh'"),
        ("E", "e — pronounced 'eh'"),
        ("F", "efe — pronounced 'eh-feh'"),
        ("G", "ge — before e or i, like English 'h'; otherwise hard 'g'"),
        ("H", "hache — silent letter"),
        ("I", "i — pronounced 'ee'"),
        ("J", "jota — like English 'h' in hello"),
        ("K", "ka — pronounced 'kah'"),
        ("L", "ele — pronounced 'eh-leh'"),
        ("LL", "elle — pronounced 'ye' or 'zh' depending on region"),
        ("M", "eme — pronounced 'eh-meh'"),
        ("N", "ene — pronounced 'eh-neh'"),
        ("Ñ", "eñe — pronounced 'enye', like 'ny' in canyon"),
        ("O", "o — pronounced 'oh'"),
        ("P", "pe — pronounced 'peh'"),
        ("Q", "cu — pronounced 'koo' (always followed by 'u')"),
        ("R", "ere — single r, soft roll"),
        ("RR", "erre — rolled or trilled r"),
        ("S", "ese — pronounced 'eh-seh'"),
        ("T", "te — pronounced 'teh'"),
        ("U", "u — pronounced 'oo'"),
        ("V", "uve — almost like 'b', pronounced 'oo-beh'"),
        ("W", "uve doble — pronounced 'oo-beh doble' or 'doble ve'"),
        ("X", "equis — pronounced 'eh-kees'"),
        ("Y", "i griega — pronounced 'ee gree-eh-gah' or 'ye'"),
        ("Z", "zeta — 'th' in Spain, 's' in Latin America"),
    ],
    "Days of the Week": [
        ("Monday", "lunes"),
        ("Tuesday", "martes"),
        ("Wednesday", "miércoles"),
        ("Thursday", "jueves"),
        ("Friday", "viernes"),
        ("Saturday", "sábado"),
        ("Sunday", "domingo"),
        ("the week", "la semana"),
        ("the weekend", "el fin de semana"),
        ("today", "hoy"),
        ("tomorrow", "mañana"),
        ("yesterday", "ayer"),
        ("What day is it today?", "¿Qué día es hoy?"),
        ("It’s Monday", "Es lunes"),
        ("See you on Monday", "Hasta el lunes"),
        ],

    "Famous People & Examples": [
        ("Germaine Franco", "Germaine Franco"),
        ("José Andrés Puerta", "José Andrés Puerta"),
        ("Ana de Armas", "Ana de Armas"),
        ("Inti Castro", "Inti Castro"),
        ("Vero Boquete", "Vero Boquete"),
        ("Pablo Picasso was a Spanish artist", "Pablo Picasso fue un artista español"),
        ("Inti Castro is a Chilean urban artist", "Inti Castro es una artista urbana chilena"),
    ],

    "Languages & Culture": [
        ("Some Spanish-speaking countries have more than one official language", "Algunos países hispanohablantes tienen más de una lengua oficial"),
        ("Bolivia: Spanish, Quechua, Aymara, Guaraní and 34 other indigenous languages", "Bolivia: español, quechua, aimara, guaraní y otras 34 lenguas originarias"),
        ("Paraguay: Spanish and Guaraní", "Paraguay: español y guaraní"),
        ("Peru: Spanish, Quechua, Aymara and other indigenous languages", "Perú: español, quechua, aimara y otras lenguas originarias"),
        ("Spain: Spanish, Catalan, Galician, Basque and Aranese", "España: español, catalán, gallego, euskera y aranés"),
        ("Equatorial Guinea: Spanish, French and Portuguese", "Guinea Ecuatorial: español, francés y portugués"),
        ("Does your country have more than one official language?", "¿En tu país hay más de una lengua oficial?"),
        ("Do you know other countries with several official languages?", "¿Conoces otros países con varias lenguas oficiales?"),
        ("Quechua", "quechua"),
        ("Aymara", "aimara"),
        ("Guaraní", "guaraní"),
        ("indigenous languages", "lenguas originarias"),
        ("Catalan", "catalán"),
        ("Galician", "gallego"),
        ("Basque", "euskera"),
        ("Aranese", "aranés"),
    ],

    "Leisure Activities & Language Learning": [
        ("Write leisure activities that can serve to learn or improve a language and learn about its culture", "Escribe actividades de ocio que pueden servir para aprender o mejorar un idioma y aprender sobre su cultura"),
        ("To listen to music", "Escuchar música"),
        ("To write on social networks", "Escribir en redes sociales"),
        ("To watch series and movies (in English and in French)", "Ver series y películas (en inglés y en francés)"),
        ("leisure activities", "actividades de ocio"),
        ("to learn", "aprender"),
        ("to improve", "mejorar"),
        ("a language", "un idioma"),
        ("culture", "cultura"),
        ("to listen to music", "escuchar música"),
        ("to write on social networks", "escribir en redes sociales"),
        ("to watch series and movies", "ver series y películas"),
        ("to go to a concert", "ir a un concierto"),
        ("to watch television", "ver la televisión"),
        ("to go to an exhibition", "ir a una exposición"),
        ("to go out at night", "salir de noche"),
        ("to visit historical places", "visitar lugares históricos"),
        ("to go to the cinema", "ir al cine"),
        ("to go out for dinner", "salir a cenar"),
        ("to cook", "cocinar"),
        ("to go shopping", "ir de compras"),
        ("to go to the beach", "ir a la playa"),
        ("to read", "leer"),
        ("to play video games", "jugar a videojuegos"),
        ("to go on an excursion", "ir de excursión"),
        ("to take a theater course", "hacer un curso de teatro"),
        ("to go to the theater", "ir al teatro"),
        ("to go out with friends", "salir con amigos"),
        ("to visit family", "visitar a la familia"),
        ("to learn languages", "aprender idiomas"),
        ("to dance", "bailar"),
        ("I go out", "salgo"),
        ("I play", "juego"),
        ("to learn other languages", "aprender otros idiomas"),
        ("to live in a Spanish-speaking country", "vivir en un país hispanohablante"),
        ("to have Spanish-speaking friends", "tener amigos/as de habla hispana"),
        ("to work in a Spanish-speaking country", "trabajar en un país de habla hispana"),
        ("to spend vacation in a Spanish-speaking country", "pasar las vacaciones en un país hispanohablante"),
        ("to study at a Latin American university", "estudiar en una universidad hispanoamericana"),
        ("to dance flamenco", "bailar flamenco"),
        ("to be a police officer", "ser policía"),
        ("to visit Barcelona", "visitar Barcelona"),
        ("to meet up with friends", "quedar con amigos"),
        ("to go to a party", "ir a una fiesta"),
        ("to travel to Yucatán", "viajar a Yucatán"),
        ("to walk with the dog", "caminar con el perro"),
        ("to rest", "descansar"),
        ("to sleep", "dormir"),
        ("to watch a movie", "ver una película"),
        ("to have a coffee", "tomar un café"),
        ("to walk / to go for a walk", "caminar / pasear"),
        ("to read a book", "leer un libro"),
        ("to do exercise", "hacer ejercicio"),
        ("to sleep a lot", "dormir mucho"),
        ("to go to the park", "ir al parque"),
        ("to dance salsa", "bailar salsa"),
        ("to visit Buenos Aires every year", "visitar Buenos Aires cada año"),
        ("to cook Spanish dishes", "cocinar platos españoles"),
        ("to listen to music in Spanish", "escuchar música en español"),
        ("to watch Spanish movies", "ver películas en español"),
        ("I want to visit Colombia to dance salsa", "Quiero visitar Colombia para bailar salsa"),
        ("I want to visit Colombia because I want to dance salsa", "Quiero visitar Colombia porque quiero bailar salsa"),
        ("I want to visit Germany because I want to speak German", "Quiero visitar Alemania porque quiero hablar alemán"),
        ("I want to visit Colombia because I want to eat tostones", "Quiero visitar Colombia porque quiero comer tostones"),
    ],

    "Reasons & Purposes (Por vs Para)": [
        ("for work (reason)", "por trabajo"),
        ("for studies (reason)", "por estudios"),
        ("for pleasure (reason)", "por placer"),
        ("for his/her work", "por su trabajo"),
        ("for his/her studies", "por su estudios"),
        ("for his/her pleasure", "por su placer"),
        ("to read in Spanish (purpose)", "para leer en español"),
        ("to work (purpose)", "para trabajar"),
        ("to travel (purpose)", "para viajar"),
        ("to practice (purpose)", "para practicar"),
        ("to speak (purpose)", "para hablar"),
        ("to visit (purpose)", "para visitar"),
        ("to chat with friends (purpose)", "para chatear con su amigos"),
        ("because his/her boyfriend is Colombian", "porque su novio es colombiano"),
        ("because he/she wants to live in Costa Rica", "porque quiere vivir en costa rica"),
        ("Why do you think they do it?", "por qué crees que lo hacen?"),
        ("Andre studies Spanish to travel", "Andre estudiar español para viajar"),
    ],

    "Future Plans & Desires": [
        ("Which of these things do you want to do in the future?", "cuáles de estas cosas quieres hacer en el futuro?"),
        ("Choose two", "elige dos"),
        ("Learn other languages", "aprender otros idiomas"),
        ("live in a Spanish-speaking country", "vivir en un país hispanohablante"),
        ("have Spanish-speaking friends", "tener amigos/as de habla hispana"),
        ("work in a Spanish-speaking country", "trabajar en un país de habla hispana"),
        ("spend vacation in a Spanish-speaking country", "pasar las vacaciones en un país hispanohablante"),
        ("study at a Latin American university", "estudiar en una universidad hispanoamericana"),
        ("Spanish-speaking", "hispanohablante"),
        ("Latin American", "hispanoamericano"),
        ("Latin American", "latinoamericano"),
        ("I want to have Spanish-speaking friends", "yo quiero tener amigos de habla hispana"),
        ("My classmate Nial wants to spend vacation in a Spanish-speaking country", "mi compañero Nial quiere pasar las vacaciones en un país hispanohablante"),
        ("Nial and I want to spend vacation in a Spanish-speaking country", "Nial y yo queremos pasar las vacaciones en un país hispanohablante"),
        ("Bob and Alice want to work in a Spanish-speaking country", "Bob y Alice quieren trabajar en un país de habla hispana"),
    ],

    "Talking About Reasons to Study Spanish": [
        ("Why do you study Spanish?", "¿Por qué estudias español?"),
        ("I study Spanish because...", "Estudio español porque..."),
        ("What are your reasons for studying Spanish?", "¿Cuáles son tus razones para estudiar español?"),
        ("My reasons for studying Spanish are...", "Mis razones para estudiar español son..."),
        ("Let's talk about the reasons to study Spanish", "Vamos a hablar sobre las razones para estudiar español"),
        ("One reason to study Spanish is...", "Una razón para estudiar español es..."),
        ("Another reason is...", "Otra razón es..."),
        ("The main reason", "la razón principal"),
        ("Spanish is useful for travel", "el español es útil para viajar"),
        ("Spanish opens career opportunities", "el español abre oportunidades profesionales"),
        ("Spanish connects you with culture", "el español te conecta con la cultura"),
        ("Spanish helps you communicate with millions of people", "el español te ayuda a comunicarte con millones de personas"),
        ("Spanish is the second most spoken language", "el español es la segunda lengua más hablada"),
        ("I want to understand Spanish movies without subtitles", "quiero entender las películas en español sin subtítulos"),
        ("I want to read books in Spanish", "quiero leer libros en español"),
        ("Spanish will help me in my job", "el español me ayudará en mi trabajo"),
        ("I love Spanish culture", "me encanta la cultura española"),
        ("Spanish is a beautiful language", "el español es un idioma hermoso"),
        ("Learning Spanish is fun", "aprender español es divertido"),
        ("Spanish grammar is logical", "la gramática del español es lógica"),
    ],

    "Querer Practice": [
        ("I want to eat", "quiero comer"),
        ("You want to sleep", "quieres dormir"),
        ("He wants to study", "él quiere estudiar"),
        ("She wants to travel", "ella quiere viajar"),
        ("We want to learn", "queremos aprender"),
        ("You all want to dance", "queréis bailar"),
        ("They want to work", "ellos quieren trabajar"),
        ("Do you want coffee?", "¿quieres café?"),
        ("I don't want to go", "no quiero ir"),
        ("What do you want?", "¿qué quieres?"),
        ("I want more time", "quiero más tiempo"),
        ("She wants a new job", "ella quiere un trabajo nuevo"),
        ("We want to be happy", "queremos ser felices"),
        ("They don't want problems", "no quieren problemas"),
        ("I want to speak Spanish well", "quiero hablar español bien"),
        ("Do you want to come with me?", "¿quieres venir conmigo?"),
        ("What do they want to do?", "¿qué quieren hacer?"),
        ("I want to understand everything", "quiero entender todo"),
        ("You want to live here", "quieres vivir aquí"),
        ("We want the same thing", "queremos lo mismo"),
        ("To practice the verb querer", "Practicar el verbo querer"),
    ],

    "Cultural Festivals & Events": [
        ("San Fermín in Pamplona", "San Fermín en Pamplona"),
        ("San Juan festival in Santander", "San Juan fiesta en Santander"),
        ("La Tomatina", "La Tomatina"),
        ("Las Fallas de Valencia", "las Fallas de Valencia"),
        ("Festival of Flowers Medellín", "festival de las flores Medellín"),
        ("Carnival of Blacks and Whites", "carnaval de negros y blancos"),
        ("in England a famous festival is bonfire", "en Inglaterra un festival de famous esta hoguera / fogata"),
    ],

    "Sample Introductions": [
        ("Hello, my name is Connor and I am 29 years old. I am Irish, from Dublin.", "Hola, me llamo Connor y tengo 29 años. Soy irlandés, de Dublín."),
        ("I speak Spanish, but I want to improve because I live in Spain.", "Hablo español, pero quiero mejorar porque vivo en España."),
        ("I read many books in Spanish and watch series and movies in Spanish, but I want to do an exchange with a native speaker to speak better.", "Leo muchos libros en español y veo series y películas en español, pero quiero hacer un intercambio con un nativo para hablar mejor."),
    ],
}
